# Generated by Django 5.2.17

from django.db import migrations, models


def classify_existing_logs(apps, schema_editor):
    AuditLog = apps.get_model("auditlog", "AuditLog")
    AuditLog.objects.filter(action__startswith="PLATFORM_").update(scope="platform")


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="scope",
            field=models.CharField(choices=[("workspace", "Workspace"), ("platform", "Platform")], db_index=True, default="workspace", max_length=20),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["tenant", "scope", "created_at"], name="auditlog_au_tenant__b8c9e1_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["scope", "created_at"], name="auditlog_au_scope_7f2a11_idx"),
        ),
        migrations.RunPython(classify_existing_logs, migrations.RunPython.noop),
    ]
