# Generated by Django 5.2.17 on 2026-08-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_auditlog_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_tenant__dc7c36_idx',
            old_name='auditlog_au_tenant__b8c9e1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_scope_4f581d_idx',
            old_name='auditlog_au_scope_7f2a11_idx',
        ),
    ]
