# Generated by Django 5.2.17 on 2026-08-17 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_markets', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('audit_config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'domain'], name='websites_we_tenant__996f82_idx'), models.Index(fields=['tenant', 'status', 'updated_at'], name='websites_we_tenant__414c0b_idx')],
                'unique_together': {('tenant', 'domain')},
            },
        ),
    ]
