# Generated by Django 5.2.17 on 2026-08-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_keywordrankrun_ai'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditfixrun',
            name='websites_au_tenant__fix_cr_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordrankrun',
            name='websites_ke_tenant__kw_cr_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteaccess',
            name='websites_we_tenant__acc_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='auditfixrun',
            new_name='websites_au_tenant__b1d1f3_idx',
            old_name='websites_au_tenant__fix_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordrankrun',
            new_name='websites_ke_tenant__5e9d89_idx',
            old_name='websites_ke_tenant__kw_idx',
        ),
        migrations.RenameIndex(
            model_name='websiteaccess',
            new_name='websites_we_tenant__d73177_idx',
            old_name='websites_we_tenant__access_idx',
        ),
    ]
