export type DocsBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "callout"; tone: "info" | "warning" | "success"; title: string; text: string }
  | { type: "steps"; items: Array<{ title: string; body: string }> }
  | { type: "table"; headers: string[]; rows: string[][] };

export type DocsPage = {
  slug: string[];
  href: string;
  title: string;
  description: string;
  group: string;
  blocks: DocsBlock[];
};

function href(slug: string[]) {
  return slug.length ? `/docs/${slug.join("/")}` : "/docs";
}

function page(slug: string[], title: string, description: string, group: string, blocks: DocsBlock[]): DocsPage {
  return { slug, href: href(slug), title, description, group, blocks };
}

export const DOCS_PAGES: DocsPage[] = [
  page(
    [],
    "Seonet user guide",
    "How the established website-intelligence modules and the newer growth modules work together in one workspace.",
    "Getting started",
    [
      { type: "p", text: "Seonet is a workspace for growth teams. It is not a pile of disconnected tools. You connect a website, understand your own business, read a market only when you have evidence, record opportunities, find matching leads, work them in CRM, and optionally plan campaigns against lists you already have." },
      { type: "callout", tone: "info", title: "One product, two module families", text: "Established modules cover website intelligence: properties, crawls, SEO, AEO/GEO, and performance. Newer growth modules sit upstream of Leads: Business Analysis, Market Intelligence, Opportunities, then the same Leads product, CRM, and Marketing. Seonet does not add a second lead finder." },
      { type: "h2", text: "What you will find in this guide" },
      { type: "ul", items: ["How a workspace, package, and module assignment control what you see.", "The operating loop from business data (CSV or store sync) to market evidence to opportunities to leads to CRM.", "Each established module: websites, audits, SEO, keyword ranks, AEO/GEO, and performance.", "Each growth module: business, e-commerce stores, markets, opportunities, leads, CRM, and marketing.", "Ask Seonet, reports, integrations, billing, and team settings.", "What Seonet will never invent: revenue, city grades, open rates, Google #1 ranks, or contact details." ] },
      { type: "h2", text: "Who this is for" },
      { type: "p", text: "This guide is written for workspace owners, managers, analysts, sales, and marketing users. It describes what you do in the product, not how the platform is engineered. Platform operators who assign packages and modules should still start here, then use Subscription and the control plane for entitlements." },
      { type: "h2", text: "Start here" },
      { type: "steps", items: [
        { title: "Create or join a workspace", body: "Register, or accept an invite. Your role (owner, admin, manager, analyst, sales, marketing, or viewer) decides which actions you can take even when a module is on the package." },
        { title: "Confirm your package modules", body: "Open Subscription. Navigation only lists modules assigned to this workspace. Direct URLs to a module that is not on the package show a package message instead of empty fake data." },
        { title: "Follow the loop that matches your job", body: "Website teams start with Websites and Audits. Growth teams start with Business Analysis (connect a store or import CSV), then Markets and Opportunities, then Leads. Sales works CRM. Marketing records campaigns against existing lists or stored customers." },
      ] },
    ],
  ),
  page(
    ["how-it-works"],
    "How Seonet works",
    "The established intelligence stack and the newer growth loop, and how they share one tenant without mixing their numbers.",
    "Getting started",
    [
      { type: "p", text: "Think of Seonet as two complementary systems in the same login. Website Intelligence tells you how a connected property is performing. Growth intelligence tells you where your own business and market evidence point next. They share the workspace, team, and billing. They do not share scores." },
      { type: "h2", text: "Established modules (website intelligence)" },
      { type: "p", text: "These modules have been the core of Seonet: add a website, run an audit, inspect SEO, AEO/GEO, and technical performance, then print a branded report. Scores come from crawled pages and HTTP measurements. The website “opportunity” score is an audit finding score. It is not a growth Opportunity record and not a CRM deal." },
      { type: "ul", items: ["Websites — properties you own or operate.", "Audits — queued crawls with issues, recommendations, and history.", "SEO — on-page and technical SEO from the latest completed audit.", "Keyword ranks — background check of stored SEO keywords against a licensed first-page sample, plus package-gated suggestions.", "AEO/GEO — answer-engine and generative-engine readiness from the same crawl.", "Performance — TTFB and page-level technical health from live HTTP, not a Lighthouse placeholder."] },
      { type: "h2", text: "Newer modules (growth loop)" },
      { type: "p", text: "These modules were added so Seonet can answer “what should we sell, where, and to whom” without inventing a league table of cities. They feed the existing Leads module. They do not replace it." },
      { type: "ol", items: ["Business Analysis — your profile plus products, customers, and orders from CSV or a store sync. Revenue KPIs appear only after orders exist.", "Market Intelligence — Market Brief cites served cities and ingested signals. Pakistan geography is reference data. City scores stay empty until this workspace ingests sources.", "Opportunities — evidence-backed growth records. Separate from CRM deals.", "Leads — still the only lead product: ICP, discovery, lists, scoring, enrichment. Store buyers can be copied into Leads; they are existing customers, not scraped prospects.", "CRM — companies, contacts, deals, activities, and a funnel from stored deals.", "Marketing — campaigns whose audience is a live count of list members, imported customers in a city, or leads already linked to an opportunity."] },
      { type: "h2", text: "How the loop is supposed to run" },
      { type: "steps", items: [
        { title: "Describe the business", body: "Save the business type, industry, current market, and goal. Connect Shopify, WooCommerce, Etsy, or eBay, or download a CSV template, fill it, and import. Test, then Sync a store. Until placed orders exist, sales KPIs stay hidden." },
        { title: "Read served vs expansion from stored rows", body: "After a sync or orders import, Seonet analyzes where you already sell, which catalog items sell, and where to investigate next — only with stored evidence. It does not invent city demand grades." },
        { title: "Read the market only with signals", body: "Open Market Brief. Ask a question; answers cite stored commerce and ingested signals. Browse places as names. Download the signals template, fill licensed or operator values, then import. Scoring weights are yours to set. No signals means no score — not a default 50." },
        { title: "Record an opportunity with evidence", body: "Write why this opportunity exists. Generate from evidence (and store sync) creates rows from served cities, thin books, product-city gaps, unsold catalog, weak reviews, or ingested scores. Link existing Seonet leads; do not expect Seonet to invent a prospect list here." },
        { title: "Find leads in the Leads module", body: "Confirm an ICP. Optionally pass a market city from an opportunity into discovery. Discovery uses enabled platform lead sources. Copy buyers into Leads copies stored commerce customers; they are existing buyers, not scraped prospects. Enrichment rescores completeness; it does not invent email or phone." },
        { title: "Promote into CRM", body: "Add to CRM creates a company and deal in the native pipeline. Stage changes are real API updates. The funnel counts stored deals only. There is no win-rate forecast." },
        { title: "Plan a campaign from people you already have", body: "Pick a lead list, imported or synced customers in a city, or opportunity-linked leads. Record send snapshots the live count. Seonet does not send email or SMS and does not invent open rates." },
      ] },
      { type: "callout", tone: "warning", title: "Do not mix these numbers", text: "Dashboard “Website opportunity” is from audit findings. “Growth opportunities” are recorded evidence rows. “CRM deals” are native pipeline deals. “Commerce orders / served cities / expansion cities” are Business Analysis stored facts. Ask Seonet will refuse questions that require invented future revenue." },
    ],
  ),
  page(
    ["packages"],
    "Packages, modules, and access",
    "Why a screen can be missing, why an API can be blocked, and which default packages include which modules.",
    "Getting started",
    [
      { type: "p", text: "A package is the commercial entitlement on the workspace. A module is a product area (Business Analysis, Leads, CRM, and so on). A role is what a person may do inside those areas. You need the module on the package and the permission on the role." },
      { type: "h2", text: "Default packages" },
      { type: "table", headers: ["Package", "What it is for", "Modules included by default"], rows: [
        ["Starter", "Website intelligence plus the growth analysis layers, without lead discovery or CRM.", "Websites, Audits, Business, Markets, Opportunities"],
        ["Growth", "Turn analysis into pipeline.", "Starter modules plus Leads, CRM, Reports, Marketing"],
        ["Scale", "Commercial suite with AI and integrations.", "Growth modules plus Integrations and AI"],
        ["Enterprise", "All modules including AEO/GEO, custom limits, commercial terms.", "All modules"],
      ] },
      { type: "p", text: "SI Global can override modules per workspace in the control plane. Your Subscription page lists the modules actually assigned, not a marketing brochure." },
      { type: "callout", tone: "info", title: "Store connections vs Integrations vs AI", text: "Shopify, WooCommerce, Etsy, and eBay require the Business module (Starter and above). HubSpot, Odoo, Sheets, webhooks, and custom API require the Integrations module (Scale and Enterprise by default). AI-drafted Business Expert language and AI keyword suggestions require the AI module plus remaining package AI credits. Licensed Google Custom Search or SerpAPI keys live in the platform console, not on the tenant." },
      { type: "h2", text: "What happens when a module is off" },
      { type: "ul", items: ["It disappears from the left navigation and the command palette.", "Opening the URL shows “Not on this package” and a link to Subscription.", "The API returns a feature-disabled error. Seonet does not return sample KPIs to fill the gap."] },
      { type: "h2", text: "Roles (simplified)" },
      { type: "ul", items: ["Owner and Admin — full workspace permissions.", "Manager — operate growth, intelligence, CRM, and marketing without deleting members or changing roles.", "Analyst — view and audit; export reports; cannot run discovery as a creator in every area.", "Sales Manager / Representative — leads and CRM.", "Marketing User — campaigns plus view access to business, markets, opportunities, and leads.", "Viewer — read-only view permissions."] },
      { type: "callout", tone: "info", title: "Ask Seonet is always in the nav", text: "Ask maps questions to allowlisted workspace counts. It does not require the AI module. AI only optionally remaps a question onto that same allowlist. Advisors still return facts when AI is off, plus a recommendation to enable AI for drafted copy." },
    ],
  ),
  page(
    ["facts"],
    "Facts, inferences, and what Seonet will not invent",
    "The honesty rules that apply to both established and newer modules.",
    "Getting started",
    [
      { type: "p", text: "Seonet is designed so empty is honest. If a number is not in your workspace, screens stay empty or show a reason. AI output is tagged so you can tell a stored fact from a suggestion." },
      { type: "h2", text: "Labels you will see" },
      { type: "ul", items: ["FACT — counted or stored in this workspace (imported orders, lead fields, deal stages, crawl measurements).", "INFERENCE — a model remark that must not be saved as a KPI.", "RECOMMENDATION — a suggested next action.", "Origin none / estimated — market scores: none means no signals; estimated means partial coverage from ingested signals."] },
      { type: "h2", text: "Seonet will not" },
      { type: "ul", items: ["Invent last-month revenue, conversion rates, or city demand grades.", "Fill Lahore = 92 style opportunity rows without stored orders or ingested signals.", "Invent email, phone, or website on enrichment.", "Treat a store location or Pakistan geography catalog as a demand score.", "Promise a Google #1 rank or scrape google.com. Positions come only from a licensed Custom Search or SerpAPI first-page sample.", "Invent email open rates or dispatch SMS from Marketing. Export the stored audience and record send.", "Run raw SQL from Ask Seonet.", "Forecast CRM win rates. The funnel is stored deal counts and amounts by stage.", "Charge a card until Stripe or PayPal is enabled in the control plane. Default billing is invoice / bank transfer."] },
      { type: "h2", text: "CSV imports and store sync" },
      { type: "p", text: "On Business → Products and Sales, download the CSV template, fill your rows, then import the filled file. Keep the header row. Skipped rows are reported. You can also connect Shopify, WooCommerce, Etsy, or eBay and sync catalog, orders, customers, and (where the platform exposes them) reviews into the same tables. After a successful sync or orders import, Seonet runs business and product analysis and may record growth opportunities from that evidence." },
      { type: "p", text: "Store credentials stay on the server and are never shown again. Each sync stores up to 50 products, 50 orders, and 50 reviews from that platform. Amazon and other marketplaces are not connected in this release." },
    ],
  ),
  page(
    ["modules", "websites"],
    "Website Intelligence",
    "Established module. Connect properties, crawl them, and keep website health as a first-class workspace object.",
    "Established modules",
    [
      { type: "p", text: "Website Intelligence is the original Seonet spine. You add a URL you are allowed to audit. Seonet stores the site as a workspace object, queues crawls, and attaches audits, issues, recommendations, and performance pages to that site." },
      { type: "h2", text: "What you do" },
      { type: "steps", items: [
        { title: "Add a website", body: "Use Add website. Provide a public HTTP(S) URL. Seonet rejects private or non-public targets." },
        { title: "Run an audit", body: "Start an audit from the website. Progress is a real background job, not a timer animation." },
        { title: "Read the site", body: "Open issues, recommendations, audit history, keyword ranks, and technical performance for that property." },
        { title: "Check keywords in the background", body: "Save SEO keywords on the website, then open Keyword ranks. The UI only shows live job progress while Seonet checks a licensed first-page sample and drafts suggestions." },
      ] },
      { type: "h2", text: "How it relates to newer modules" },
      { type: "p", text: "A strong website does not automatically create a growth Opportunity or a lead. Use Business and Markets when you want expansion evidence. Use Leads when you want prospects. Website scores stay on the website." },
      { type: "callout", tone: "info", title: "Dashboard website scores", text: "Website health, SEO, AEO, GEO, performance, and website opportunity on the dashboard come from the latest completed audit. They stay blank until an audit finishes. Commerce orders, served cities, and expansion cities come from Business Analysis stored rows, not from the website crawl." },
    ],
  ),
  page(
    ["modules", "audits"],
    "Audits, SEO, AEO/GEO, and Performance",
    "Established scoring from crawls and live HTTP. Explainable issues, not a black-box grade.",
    "Established modules",
    [
      { type: "p", text: "An audit is a completed (or running) analysis of a website. Scores are deterministic from crawled content and measured responses. You can open issues by severity, mark issue status, and print a branded intelligence report." },
      { type: "h2", text: "SEO" },
      { type: "p", text: "The SEO screen summarizes technical and on-page SEO from completed audits. Empty means no completed audit, not a default C grade." },
      { type: "h2", text: "Keyword ranks" },
      { type: "p", text: "Open Keyword ranks from a website, SEO, or AEO. Check keywords runs as a background job and only shows live progress. Positions come from a licensed Google Custom Search or SerpAPI first-page sample — not from scraping google.com. Scale and Enterprise then draft extra queries with Claude or another enabled provider. Starter and Growth keep heuristic variants. See Keyword ranks and suggestions for the full steps." },
      { type: "h2", text: "AEO / GEO" },
      { type: "p", text: "AEO (answer engines) and GEO (generative engines) measure readiness beyond classic ten-blue-links SEO. This module is on Enterprise by default; other packages may receive it as an override. The AEO dashboard still only shows crawl-derived scores." },
      { type: "h2", text: "Performance" },
      { type: "p", text: "Technical Performance uses live HTTP: TTFB, page scores, size, redirects, compression, protocol. You can export the page table as CSV and compare crawls. Seonet does not substitute a Lighthouse placeholder." },
      { type: "h2", text: "Printable audit report" },
      { type: "p", text: "Open an audit report to print with platform branding, workspace name, and date. You can also download issues as CSV or the report as JSON. This is a workspace intelligence report, not a public marketing prospectus." },
      { type: "h2", text: "Connect access and apply recommended fixes" },
      { type: "p", text: "After a completed audit you can opt in to connect WordPress (application password), cPanel FTP, FTP, or SFTP/VPS. Seonet tests the login, stores the secret on the server, and only then applies allowlisted fixes (robots.txt, sitemap, title, meta, canonical, social tags, language, viewport, Organization/WebSite JSON-LD). The first audit is kept as the baseline. A new crawl re-checks SEO, AEO, and GEO. Progress is the score and issue delta — not a Google ranking. Performance, HTTPS, and invented copy are never written. Disconnect anytime." },
    ],
  ),
  page(
    ["modules", "websites", "keywords"],
    "Keyword ranks and suggestions",
    "Background check of stored SEO keywords against a licensed first-page sample, then package-gated suggestions for search engines and AI-agent queries.",
    "Established modules",
    [
      { type: "p", text: "Keyword ranks sit on a website you already added. Seonet does not scrape google.com and does not promise a #1 rank. The screen only shows live job progress while the work runs in the background." },
      { type: "h2", text: "What you do" },
      { type: "steps", items: [
        { title: "Save keywords on the website", body: "Add comma-separated SEO keywords when you create the site, or keep them on the website record. Target markets and industry improve both the sample queries and the suggestions. A completed audit also lets Seonet use the homepage title if the keyword list is thin." },
        { title: "Start Check keywords in the background", body: "Open the website, SEO, or AEO screen and choose Keyword ranks. The job stages are: collecting keywords, checking search results, drafting suggestions, then completed. You can leave the page; progress stays in the same job panel as audits." },
        { title: "Read the first-page sample", body: "Each stored query shows a position only when this domain appeared in the licensed first-page sample. “Not in sample” means the domain was not in that sample. It is not a claim that you rank on page two or that you will never rank." },
        { title: "Read suggested queries", body: "Heuristic rows are tagged recommendation or fact (question forms, “best” modifiers, industry + market, catalog product names). On Scale and Enterprise, Claude or another enabled provider adds inference rows from the business profile, catalog, last working SEO audit, and the sample outcomes. Nothing is stored as a promised rank." },
      ] },
      { type: "h2", text: "Where positions come from" },
      { type: "p", text: "SI Global enables Google Custom Search (API key plus Programmable Search Engine ID) or SerpAPI in the platform console. Those keys stay on the server. Every workspace uses the licensed source. If neither source is enabled, the job still completes: positions stay empty with a reason, and suggestions still appear." },
      { type: "callout", tone: "warning", title: "Not a live Google scrape", text: "Seonet never fetches google.com HTML. A first-page sample is not the full index and not a guaranteed ranking report. Competitors listed on the website are context only; Seonet does not invent their ranks either." },
      { type: "h2", text: "What Seonet collects" },
      { type: "ul", items: [
        "Stored website keywords, up to a small set so licensed API cost stays bounded.",
        "Homepage title from the latest completed audit when it is not already in the list.",
        "Keyword + saved target market combinations (for example, industrial pumps in Karachi).",
      ] },
      { type: "h2", text: "Suggestions by package" },
      { type: "table", headers: ["Package", "What you get", "AI"], rows: [
        ["Starter", "Heuristic question, “best”, and market variants from stored keywords, industry, and catalog product names.", "Off. The screen explains that package AI is on Scale and Enterprise."],
        ["Growth", "The same heuristic set. Growth has leads and CRM, not the AI module by default.", "Off unless SI Global assigns the AI module to this workspace."],
        ["Scale", "Heuristic set plus extra queries drafted by Claude, OpenAI, Grok, or Gemini — whichever key is enabled.", "On. Uses remaining package AI credits."],
        ["Enterprise", "Same as Scale, plus AEO/GEO on the package by default.", "On. Uses remaining package AI credits."],
      ] },
      { type: "p", text: "AI suggestions use the same shared platform key and the same credit meter as Ask advisors and Business Expert language. One token is one package credit. When the period limit is reached, the job still finishes: heuristic queries remain and the keywords page shows the credit reason. Tenants never paste their own Claude key." },
      { type: "h2", text: "What the AI is allowed to use" },
      { type: "ul", items: [
        "FACT lines only: domain, industry, description, stored keywords, target markets, competitors, business profile, catalog product names.",
        "Working SEO from the last completed audit: scores, homepage title, H1, meta, and open SEO/content issues.",
        "Licensed sample outcomes: which stored queries included this domain on the first page, and which did not.",
      ] },
      { type: "callout", tone: "info", title: "Inference is not a forecast", text: "AI-drafted queries are tagged inference. Heuristic “what is …” and “best …” rows are recommendations. Seonet will not write that a query will reach page one, invent traffic, or invent products and cities that are not in the FACT list." },
      { type: "h2", text: "How this relates to other modules" },
      { type: "ul", items: [
        "Website Intelligence and Audits — keyword ranks attach to a site. They do not overwrite audit scores.",
        "Apply recommended fixes — changes SEO/AEO/GEO on the site. That is a score compare against the first audit, not a Google rank.",
        "Business Analysis — profile, industry, and catalog products improve suggestions. Empty catalog means those FACT lines stay empty.",
        "AEO/GEO — question-form suggestions are for answer-engine and AI-agent search readiness. They are not an AEO score.",
      ] },
    ],
  ),
  page(
    ["modules", "business"],
    "Business Analysis",
    "Newer module. Profile, first-party commerce (CSV or store sync), then business and product analysis from stored rows.",
    "Growth modules",
    [
      { type: "p", text: "Business Analysis is about your company, not the internet. CRM companies are prospects. Commerce customers and orders are first-party buyers you import or sync from a store. Do not expect sample cities or demo revenue." },
      { type: "h2", text: "Screens" },
      { type: "ul", items: [
        "Overview — save the profile, see KPIs when placed orders exist, then served markets, product research, and next actions.",
        "Sales — order rows from CSV or sync. Channel shows csv, shopify, woocommerce, etsy, or ebay.",
        "Products — catalog plus top sellers, unsold SKUs, product-city gaps, and weak star ratings.",
        "Customers — first-party buyers. Copy buyers into Leads copies stored name/email/city into the existing Leads module.",
        "E-Commerce — connect stores, test, sync, then the full analysis. Run business analysis anytime after data exists.",
        "Geography — where you are serving, thin books, and where to investigate serving next.",
        "AI Advisor — facts from stored rows, then INFERENCE / RECOMMENDATION. Print uses the shared letterhead.",
      ] },
      { type: "h2", text: "Business profile" },
      { type: "p", text: "Save business type (e-commerce, retail, services, B2B, manufacturing), industry, category, current market, and goal. This is qualitative context for advisors. It does not create KPIs by itself. If current market has zero placed orders, analysis lists it as a profile gap to investigate — not as a demand grade." },
      { type: "h2", text: "How data gets in" },
      { type: "ul", items: [
        "CSV — on Products, Sales, or E-Commerce, Download template, fill your rows under the header, then Import filled CSV. Excel semicolon and Unicode files are accepted. Keep the header names. Import runs as a live job with the same progress dialog as website audits. Products: name, sku, category, unit_price, cost_price. Orders: one row per line item, including customer_name, city, sku, product_name, quantity, unit_price. Skipped rows are reported with a reason. Customers come from the orders file.",
        "Store sync — Shopify, WooCommerce, Etsy, or eBay. See E-commerce store connections.",
      ] },
      { type: "h2", text: "What runs after sync or an orders import" },
      { type: "p", text: "Seonet counts stored placed orders and line items, then writes a Business Expert / Product Research pass. The dashboard shows commerce orders, served cities, and expansion cities with evidence. A workspace notification links back to E-Commerce." },
      { type: "h3", text: "Where you are serving" },
      { type: "p", text: "Cities that appear on placed orders, with order counts and line revenue. This is a FACT of stored geography." },
      { type: "h3", text: "Thin served books" },
      { type: "p", text: "A city whose stored order count is much smaller than the busiest stored city. That is a count comparison, not a demand grade." },
      { type: "h3", text: "Where to investigate serving" },
      { type: "p", text: "Only with evidence: profile current market with no orders; customers in a city that has no orders; a top product missing in a city that already buys other SKUs; or a city with an ingested market score and zero orders. Seonet does not invent a new city league table." },
      { type: "h3", text: "Product research" },
      { type: "p", text: "Top sellers by stored line revenue, unsold catalog rows (zero placed lines), product-city gaps, and 1–2 star reviews. Sentiment is counted from stored star ratings (4–5 positive, 3 mixed, 1–2 negative). WooCommerce and Etsy can sync reviews. Shopify and eBay do not expose reviews in this sync." },
      { type: "h2", text: "Opportunities from this module" },
      { type: "p", text: "Sync, orders import, Run business analysis, and Opportunities → Generate from evidence can record rows such as deepen coverage in a served city, grow a thin book, investigate serving an evidenced city, offer a SKU where other products already sell, review unsold catalog, or improve a product after negative reviews. Revenue is not projected." },
      { type: "h2", text: "AI business advisor" },
      { type: "p", text: "The advisor lists stored facts, then inference and recommendation. It is not allowed to invent a city conversion rate. Heuristic next actions still appear when the AI module is off. Scale and Enterprise include AI by default." },
      { type: "callout", tone: "success", title: "On Starter", text: "Business Analysis and store connections are included on Starter, Growth, Scale, and Enterprise. You can profile the business, connect a store, and import CSVs before you buy Leads or CRM. Copy buyers into Leads requires the Leads module (Growth+)." },
    ],
  ),
  page(
    ["modules", "business", "stores"],
    "E-commerce store connections",
    "Connect Shopify, WooCommerce, Etsy, or eBay. Test, sync, then analysis runs on stored rows.",
    "Growth modules",
    [
      { type: "p", text: "Open Business → E-Commerce (or Integrations → E-commerce stores). Paste that platform’s API credentials, Save, Test connection, then Sync store. Secrets stay on the server and are write-only. If you do not have a store API, download the products or orders CSV template on Products, Sales, or E-Commerce, fill your rows, then import." },
      { type: "h2", text: "Shopify" },
      { type: "steps", items: [
        { title: "Create a custom app", body: "In Shopify admin open Settings → Apps and sales channels → Develop apps. Create an app named Seonet and install it on the shop." },
        { title: "Grant read scopes", body: "Turn on read_products, read_orders, and read_customers. Copy the Admin API access token." },
        { title: "Connect in Seonet", body: "Paste the shop domain (your-store.myshopify.com) and the token. Save, Test, Sync. Reviews are not imported from Shopify in this release." },
      ] },
      { type: "h2", text: "WooCommerce" },
      { type: "steps", items: [
        { title: "Create a REST key", body: "In WordPress open WooCommerce → Settings → Advanced → REST API. Add a key with Read permission." },
        { title: "Connect in Seonet", body: "Paste the public store HTTPS URL, consumer key, and consumer secret. Save, Test, Sync. Product reviews are imported when the API returns them." },
      ] },
      { type: "h2", text: "Etsy" },
      { type: "steps", items: [
        { title: "Create an Etsy app", body: "Register at etsy.com/developers. Complete OAuth 2 for your shop and copy the API keystring and access token." },
        { title: "Connect in Seonet", body: "Paste the numeric shop ID, API key, and token. Save, Test, Sync. Receipts and shop reviews are stored when the API returns them." },
      ] },
      { type: "h2", text: "eBay" },
      { type: "steps", items: [
        { title: "Create a keyset", body: "In the eBay developer account generate a user access token with sell.fulfillment scope." },
        { title: "Connect in Seonet", body: "Paste the token. Save, Test, Sync. Seller orders are stored. Reviews are not imported from eBay in this release." },
      ] },
      { type: "h2", text: "What a sync stores" },
      { type: "ul", items: [
        "Up to 50 products, 50 orders, and 50 reviews per sync from that platform.",
        "Customers from order buyer fields. Invalid emails are dropped, not invented.",
        "Channel on each order is the provider code (shopify, woocommerce, etsy, ebay).",
        "Re-sync updates the same external IDs instead of duplicating them.",
      ] },
      { type: "h2", text: "After a successful test and sync" },
      { type: "p", text: "Seonet runs the Business Expert and Product Research pass: served markets, thin books, expansion with evidence, top products, unsold catalog, review sentiment, and next actions. Growth opportunities are recorded from that evidence. If the AI module is on, drafted INFERENCE / RECOMMENDATION language is stored as expert notes, not as KPIs. You can print E-Commerce, Geography, Overview, and Advisor." },
      { type: "callout", tone: "info", title: "Not in this release", text: "Amazon and other marketplaces are not connected. Live OAuth pop-ups are not used; you paste tokens. Store location is not turned into a city demand grade. Directory scraping is not a source of leads." },
    ],
  ),
  page(
    ["modules", "markets"],
    "Market Intelligence",
    "Cited briefs over your commerce and ingested signals. Geography is a catalog. Scores exist only after this workspace ingests sources.",
    "Growth modules",
    [
      { type: "p", text: "Market Intelligence is the cited research workspace over this tenant’s own evidence. Open Market Brief to see served cities (from placed orders) next to scored cities (from ingested signals), then ask a question. Answers cite stored rows. Pakistan geography is seeded as reference names so you can talk about Lahore as a place. That is not a demand grade. Seonet does not license AlphaSense-style filings or transcripts." },
      { type: "h2", text: "Market Brief" },
      { type: "p", text: "The brief lists overlap (you serve the city and it has a score), scored cities with no orders, and FACT citations. Save industry, category, current market, and goal as the business input, then Analyze this business or Collect from market sources. Analyze and Ask run as a live job with the same progress dialog as collect and website audits. Show heatmap plots catalog cities that already have scores or served orders: orange = deepen, amber = investigate, navy = serving only. Empty cities stay unheated." },
      { type: "h2", text: "Places" },
      { type: "p", text: "Open Markets to drill geography. Place detail shows children, any signals you ingested, and a computed score. Coverage and missing parts are listed so a partial score is visible as partial." },
      { type: "h2", text: "Demand, competition, segments" },
      { type: "p", text: "These screens render ingested or collected signals of those kinds. Collect from market sources queries Wikidata population, OpenStreetMap Overpass shop counts, and every enabled lead discovery source (Places, Yelp, Foursquare, and the rest). Values are estimated from returned counts, relative among catalog cities. Empty APIs write nothing. Directory HTML scraping is not used." },
      { type: "h2", text: "Scoring" },
      { type: "p", text: "You configure weights for signal kinds. Weights apply to ingested values only. No signals → score is empty (origin none). Some signals → estimated score with missing dimensions listed." },
      { type: "h2", text: "How this feeds Leads" },
      { type: "p", text: "Discovery can take an optional market city. That adds location context to the existing lead search. It does not start a second finder or a map product. Maps and PostGIS are not part of this release." },
    ],
  ),
  page(
    ["modules", "opportunities"],
    "Opportunities",
    "Newer module. Evidence-backed growth records. Not CRM deals and not website audit opportunity scores.",
    "Growth modules",
    [
      { type: "p", text: "A growth Opportunity is a row you (or Generate from evidence) record with a title, type, evidence, and recommended action. Types include business, market, product, geographic, customer, cross-sell, and upsell." },
      { type: "h2", text: "Generate from evidence" },
      { type: "p", text: "This action (and a store sync or orders import) creates rows only from stored commerce analysis or ingested market scores: deepen coverage in a served city, grow a thin book, investigate serving a city that has evidence, offer a SKU where other products already sell, review unsold catalog, or improve a product after 1–2 star reviews. If neither commerce rows nor signals exist, created = 0. You will not get a synthetic “Lahore 92” board. Potential impact never projects revenue." },
      { type: "h2", text: "Link existing leads" },
      { type: "p", text: "On the opportunity detail, search Seonet leads and link them. Linked leads become the audience if you later create a Marketing campaign of type “Opportunity-linked leads”. Linking does not discover new companies." },
      { type: "h2", text: "Find leads" },
      { type: "p", text: "Find leads opens Lead Discovery. If the opportunity has a market place, that city is passed as an optional geo filter into the same Leads pipeline." },
      { type: "h2", text: "Status" },
      { type: "p", text: "Open, reviewing, accepted, dismissed. This is a research pipeline. Won/lost money lives in CRM deals." },
    ],
  ),
  page(
    ["modules", "leads"],
    "Leads",
    "Established module, now fed by the growth loop. Still the only lead-generation product in Seonet.",
    "Growth modules",
    [
      { type: "p", text: "Leads is unchanged as a product: describe an ICP, confirm it, discover accounts from enabled platform sources, score completeness, enrich without inventing contact fields, save lists, export CSV, and promote into CRM." },
      { type: "h2", text: "Discovery" },
      { type: "p", text: "Write what you sell. Generate ICP (heuristic, or an AI provider if keys are enabled). Confirm before a job runs. Optional market dropdown uses Market Intelligence places. Results land in this same Leads table." },
      { type: "h2", text: "Scoring and enrichment" },
      { type: "p", text: "Quality is field completeness (website, email, phone, location, industry). ICP fit compares stored industry/location to a confirmed ICP. Enrichment writes only values returned by the company website, Wikidata, enabled discovery APIs, licensed search (Custom Search or SerpAPI), or Hunter / Clearbit / Apollo keys stored in the platform console. It does not invent email, phone, or website, and it does not scrape google.com or directory HTML." },
      { type: "h2", text: "Lists and export" },
      { type: "p", text: "Saved lists are the primary Marketing audience. Export CSV (permission lead.export) downloads stored columns only, honoring the current search and status filters." },
      { type: "h2", text: "Copy buyers from Business Analysis" },
      { type: "p", text: "On Business → Customers, Copy buyers into Leads creates Seonet leads from stored commerce customers (name, email if valid, city). Source is the store or csv. They are existing buyers, not discovered prospects. This requires the Leads module. Discovery remains the path for new accounts." },
      { type: "h2", text: "Dashboard lead intelligence" },
      { type: "p", text: "When leads exist, the dashboard shows field completeness, industry and location counts, score buckets, and a 14-day create series. Empty fields stay empty. There is no predicted conversion chart." },
      { type: "callout", tone: "warning", title: "CRM Leads vs Leads", text: "Nav → CRM → Leads is deals that were promoted from Seonet leads. Nav → Leads is discovery. They are not two finders." },
    ],
  ),
  page(
    ["modules", "crm"],
    "Native CRM",
    "Established module. Companies, contacts, deals, activities, and a funnel from stored deals.",
    "Growth modules",
    [
      { type: "p", text: "Native CRM is the sales system of record inside Seonet. Promote a lead to create a company, a contact when email or phone exists, and a deal on the default pipeline. You can also add companies, contacts, deals, and activities by hand. Owners are workspace members. Expected close dates and amounts are stored values, not forecasts." },
      { type: "h2", text: "Deals and funnel" },
      { type: "p", text: "The Deals board filters to the selected pipeline, shows stored amounts on cards, and opens a deal record for name, amount, currency, company, contact, owner, expected close, priority, next step, and won or lost reason. Moving to Won or Lost stores closed_at. Stage changes call the deal API and can emit deal.updated webhooks. Delete removes the deal from the pipeline. The funnel chart is deal counts and stored amounts per stage. Seonet does not forecast close probability or invent a win rate." },
      { type: "h2", text: "Companies and contacts" },
      { type: "p", text: "Search companies and contacts. Open a company to edit name, domain, industry, location, phone, email, tags, notes, and owner, and to see related contacts and deals. Open a contact to edit name, job title, email, phone, and owner. Delete is available when you have crm.delete." },
      { type: "h2", text: "Activities and follow-ups" },
      { type: "p", text: "Log notes, calls, meetings, or tasks against a company, deal, and contact. Complete or reopen a follow-up. A due date in the past on an incomplete activity is overdue. This is a follow-up list, not a separate project tool." },
      { type: "h2", text: "Pipelines" },
      { type: "p", text: "CRM → Pipelines creates additional pipelines, renames stages, and marks won or lost outcomes. A pipeline or stage with deals cannot be deleted until those deals move. Export downloads stored companies, contacts, deals, or activities as CSV." },
      { type: "h2", text: "Reports" },
      { type: "p", text: "Reports → CRM funnel lists stored deal counts and amounts per default-pipeline stage. That is the same fact table as the Deals board. No win-rate is printed." },
      { type: "h2", text: "Integrations" },
      { type: "p", text: "Optional HubSpot/Odoo connections live under Integrations and require those modules. Native CRM keeps working without them. Lead push to HubSpot deal objects is not implied by a stage move; deal events go to webhook and custom API destinations." },
    ],
  ),
  page(
    ["modules", "marketing"],
    "Marketing",
    "Newer module. Campaigns against people you already have. Audience size is a count, not an open rate.",
    "Growth modules",
    [
      { type: "p", text: "Marketing is included from Growth upward. Create a campaign, choose an audience, write an offer, export the stored audience as CSV, and record send. Recording send does not invent open rates." },
      { type: "h2", text: "Audience types" },
      { type: "ul", items: ["Lead list — members of a saved Seonet list. Empty list → count 0.", "Imported customers in a city — Commerce customers whose city matches, from CSV or a store sync. Cities come from stored rows.", "Opportunity-linked leads — leads you linked on a growth Opportunity. Unlinked opportunity → count 0."] },
      { type: "h2", text: "Live count vs recorded send" },
      { type: "p", text: "Live count is computed now. When you Record send, Seonet snapshots that number, marks the campaign sent, writes an audit event, meters usage, and notifies you. If the list grows later, the snapshot does not change." },
      { type: "callout", tone: "warning", title: "No invented delivery", text: "Export audience downloads stored names and emails only. Record send snapshots the count. Seonet does not invent open rates or dispatch SMS." },
    ],
  ),
  page(
    ["workspace", "ask"],
    "Ask Seonet and advisors",
    "Allowlisted counts and domain advisors. Not a chatbot that invents next year’s revenue.",
    "Workspace",
    [
      { type: "p", text: "Ask Seonet sits in the main nav for every package. Type a count such as “How many leads are in this workspace?” or a market question such as “Analyze the market for my business.” Counts stay allowlisted and return immediately. Market analysis uses the saved business profile plus orders and ingested signals, and shows the same live progress dialog as Market Brief Analyze." },
      { type: "h2", text: "Questions that work" },
      { type: "ul", items: ["How many leads / qualified leads / websites / orders / products / campaigns / CRM deals / growth opportunities.", "Lead list sizes.", "How many cities have scores (ingested signals only).", "Analyze my market / where should we expand / which cities we serve — uses this tenant’s business input."] },
      { type: "h2", text: "Questions that return no facts" },
      { type: "p", text: "“What will revenue be next year in Lahore?” is refused. Intent is empty. Facts stay []. Raw SQL is never generated." },
      { type: "h2", text: "Domain advisors" },
      { type: "p", text: "Business, Market, Opportunity, Lead, and Marketing advisor pages call the same honesty rules: facts from rows, then inference and recommendation. The Business advisor also shows served markets, product research, and next actions from stored orders. Keyword ranks on Scale and Enterprise use the same gateway to draft extra queries from the business and the last working SEO audit. Without the AI module you still get facts and heuristic next actions, plus a note to enable AI for drafted language." },
      { type: "h2", text: "Platform API keys and package credits" },
      { type: "p", text: "SI Global stores Claude (or OpenAI, Grok, Gemini) once in the control plane. Every workspace uses that shared key. Tenants never paste their own key. Each completed call records prompt and completion tokens on that workspace. One token counts as one package AI credit. When the package credit limit is reached, further AI calls stop until the billing period resets or the package is upgraded. Ask Seonet still answers allowlisted counts without using credits. Keyword rank jobs still complete: heuristic suggestions remain when credits are exhausted." },
      { type: "p", text: "The platform owner can open Tenant activity in the control plane to read prompts, Ask questions, and workspace page views across all tenants. Tenant users do not see that console." },
    ],
  ),
  page(
    ["workspace", "reports"],
    "Reports, print, and usage",
    "Print branded reports from real rows. Export the catalog. Metered events stay factual.",
    "Workspace",
    [
      { type: "h2", text: "Intelligence reports" },
      { type: "p", text: "Reports (Growth and above) lists catalog entries for audits, business, markets, opportunities, marketing, websites, leads, and CRM. The business row includes order count plus served cities, expansion cities, and top-product counts from stored analysis. Each row shows whether it is ready and why it might be empty. Open jumps to that module (business opens E-Commerce). Completed audits can be printed from here." },
      { type: "p", text: "Export JSON catalog (report.export) downloads that catalog. It does not invent a PDF of fake KPIs. Business Overview, Geography, E-Commerce, Advisor, Market overviews, Opportunities, and audit reports also offer Print with shared letterhead (logo, workspace, date, footer)." },
      { type: "h2", text: "Usage" },
      { type: "p", text: "Usage lists metered events for this period: audits, leads discovered, commerce imported, campaigns recorded, leads exported, reports exported, AI requests, AI tokens, and similar. AI credits used are prompt plus completion tokens from the platform Claude/OpenAI/Grok/Gemini key, counted per workspace against the package AI credit limit. Quantities are stored events, not estimates." },
      { type: "h2", text: "Billing" },
      { type: "p", text: "Subscription is always reachable even if the workspace is locked. Self-serve requests issue an invoice. When Stripe or PayPal is enabled with stored credentials, Pay opens that gateway checkout and a webhook marks the invoice paid. Manual / bank transfer stays available. Settings → Jobs lists background work for this workspace." },
    ],
  ),
  page(
    ["workspace", "team"],
    "Team, roles, integrations, and settings",
    "Invite people, assign roles, connect optional systems, and keep the workspace branded.",
    "Workspace",
    [
      { type: "h2", text: "Team and roles" },
      { type: "p", text: "Owners invite members and assign system or custom roles. Permissions are codes such as lead.export or marketing.manage. A marketing user can run campaigns without deleting websites." },
      { type: "h2", text: "API keys" },
      { type: "p", text: "Workspace API tokens authenticate machine access to the same tenant-scoped APIs. They are not a bypass around modules or RBAC." },
      { type: "h2", text: "Integrations" },
      { type: "p", text: "Shopify, WooCommerce, Etsy, and eBay live under Business Analysis (Starter and above). Connect them on Business → E-Commerce. HubSpot, Odoo, Google Sheets, custom API, and webhooks live under Integrations and require the Integrations module (Scale and Enterprise by default). Test connection reports real status. Disconnecting a store does not delete already synced commerce rows. Disconnecting HubSpot does not delete native CRM data." },
      { type: "h2", text: "Notifications" },
      { type: "p", text: "The bell lists workspace notifications, including campaign recorded, opportunities generated from evidence, and business analysis updated after a store sync or Run business analysis. Keyword rank jobs use the same live progress panel as audits; open Keyword ranks when the job completes. Follow notification links to the relevant screen." },
    ],
  ),
  page(
    ["faq"],
    "Frequently asked questions",
    "Short answers for the questions teams ask when established and newer modules share one workspace.",
    "Workspace",
    [
      { type: "h2", text: "Why don’t I see Leads or Marketing?" },
      { type: "p", text: "They are not on Starter by default. Upgrade to Growth, or ask SI Global to enable the module on this workspace." },
      { type: "h2", text: "Why is revenue blank after I saved a business profile?" },
      { type: "p", text: "Profile fields are not commerce. Download the orders template on Sales, fill it, and import — or connect a store, Test, and Sync. KPIs stay hidden until placed orders exist." },
      { type: "h2", text: "I synced Shopify. Why is sentiment empty?" },
      { type: "p", text: "Sentiment is counted from stored star ratings. WooCommerce and Etsy can return reviews. Shopify and eBay do not expose product reviews in this sync. Empty is correct." },
      { type: "h2", text: "Why didn’t Seonet tell me to sell in a new city?" },
      { type: "p", text: "Expansion cities appear only with stored evidence: your profile current market with no orders, customers without orders, a product missing in a city that already buys other SKUs, or an ingested market score with zero orders. Seonet does not invent a city demand grade." },
      { type: "h2", text: "Is Copy buyers the same as Lead Discovery?" },
      { type: "p", text: "No. Copy buyers into Leads copies stored commerce customers into the existing Leads table. Discovery finds new accounts from enabled platform sources. There is still only one Leads module." },
      { type: "h2", text: "Can I connect Amazon?" },
      { type: "p", text: "Not in this release. Supported stores are Shopify, WooCommerce, Etsy, and eBay. CSV remains available for any other channel." },
      { type: "h2", text: "Why are all city scores empty?" },
      { type: "p", text: "Geography is a place catalog. Scores need market signals: collect from enabled lead sources plus Wikidata/OpenStreetMap, or ingest a CSV. Empty is correct when APIs return nothing." },
      { type: "h2", text: "Is CRM the same as Opportunities?" },
      { type: "p", text: "No. Opportunities are growth hypotheses with evidence. CRM deals are sales pipeline. Dashboard shows both, labeled separately." },
      { type: "h2", text: "Will discovery scrape Google Maps?" },
      { type: "p", text: "Discovery uses lead sources enabled in the platform console (Places, Yelp, OSM, licensed directories, and similar adapters). It does not scrape Google Maps. Market Brief can show a schematic heatmap of catalog cities that already have scores or served orders." },
      { type: "h2", text: "Does Keyword ranks scrape Google?" },
      { type: "p", text: "No. Positions come from a licensed Google Custom Search or SerpAPI first-page sample enabled in the platform console. A missing position means the domain was not in that sample. Seonet does not scrape google.com and does not promise a #1 rank." },
      { type: "h2", text: "Why didn’t Claude suggest keywords for my site?" },
      { type: "p", text: "AI keyword suggestions require the AI module (Scale and Enterprise by default) and remaining package AI credits. Starter and Growth still get heuristic question and market variants. If credits are used up, the job finishes and the keywords page shows the credit reason. A Claude (or OpenAI, Grok, Gemini) key must also be enabled once in the platform console." },
      { type: "h2", text: "Why are keyword positions empty after the job finished?" },
      { type: "p", text: "Either no licensed search source is enabled, the domain was not in that first-page sample, or there were no stored keywords and no homepage title from a completed audit. Empty is honest. Save keywords and ask SI Global to enable Custom Search or SerpAPI." },
      { type: "h2", text: "Did Record send email my list?" },
      { type: "p", text: "No. It stored the live audience count and a note that no email or SMS was dispatched." },
      { type: "h2", text: "Can Ask Seonet query my database?" },
      { type: "p", text: "No. Only allowlisted counts, lists, and market analysis from this tenant’s saved profile, orders, and ingested signals. Unknown questions and forecasts return no facts." },
      { type: "h2", text: "Where is the demo password documented for operators?" },
      { type: "p", text: "Local seed users are a development convenience. Production workspaces use accounts you invite. Do not reuse seed passwords in production." },
    ],
  ),
];

export const DOCS_GROUPS = ["Getting started", "Established modules", "Growth modules", "Workspace"];

export function findDoc(slug: string[] | undefined) {
  const key = (slug ?? []).join("/");
  return DOCS_PAGES.find((page) => page.slug.join("/") === key) ?? null;
}
