PERMISSION_CATALOG: list[tuple[str, str, str]] = [
    ("website.view", "View websites", "websites"),
    ("website.create", "Create websites", "websites"),
    ("website.audit", "Run website audits", "websites"),
    ("website.delete", "Delete websites", "websites"),
    ("lead.view", "View leads", "leads"),
    ("lead.create", "Create leads", "leads"),
    ("lead.enrich", "Enrich leads", "leads"),
    ("lead.export", "Export leads", "leads"),
    ("lead.delete", "Delete leads", "leads"),
    ("business.view", "View business analysis", "business"),
    ("business.manage", "Manage business profile and imports", "business"),
    ("market.view", "View market intelligence", "markets"),
    ("market.manage", "Manage market focus, scoring, and signals", "markets"),
    ("opportunity.view", "View growth opportunities", "opportunities"),
    ("opportunity.manage", "Create and update growth opportunities", "opportunities"),
    ("marketing.view", "View marketing campaigns", "marketing"),
    ("marketing.manage", "Create and send marketing campaigns", "marketing"),
    ("crm.view", "View CRM", "crm"),
    ("crm.create", "Create CRM records", "crm"),
    ("crm.update", "Update CRM records", "crm"),
    ("crm.delete", "Delete CRM records", "crm"),
    ("report.view", "View reports", "reports"),
    ("report.export", "Export reports", "reports"),
    ("integration.view", "View integrations", "integrations"),
    ("integration.configure", "Configure integrations", "integrations"),
    ("billing.view", "View billing", "billing"),
    ("billing.manage", "Manage billing", "billing"),
    ("settings.manage", "Manage settings", "settings"),
    ("job.view", "View background jobs", "jobs"),
    ("member.view", "View members", "tenants"),
    ("member.manage", "Manage members", "tenants"),
    ("role.view", "View roles", "tenants"),
    ("role.manage", "Manage roles and permissions", "tenants"),
]

VIEW_PERMISSIONS = {code for code, _, _ in PERMISSION_CATALOG if code.endswith(".view")}

ROLE_PERMISSIONS: dict[str, set[str] | str] = {
    "owner": "*",
    "admin": "*",
    "manager": {
        "website.view",
        "website.create",
        "website.audit",
        "lead.view",
        "lead.create",
        "lead.enrich",
        "lead.export",
        "business.view",
        "business.manage",
        "market.view",
        "market.manage",
        "opportunity.view",
        "opportunity.manage",
        "marketing.view",
        "marketing.manage",
        "crm.view",
        "crm.create",
        "crm.update",
        "report.view",
        "report.export",
        "integration.view",
        "job.view",
        "member.view",
        "role.view",
        "billing.view",
    },
    "analyst": {
        "website.view",
        "website.audit",
        "lead.view",
        "business.view",
        "market.view",
        "opportunity.view",
        "marketing.view",
        "report.view",
        "report.export",
        "job.view",
    },
    "sales_manager": {
        "lead.view",
        "lead.create",
        "lead.enrich",
        "lead.export",
        "opportunity.view",
        "opportunity.manage",
        "crm.view",
        "crm.create",
        "crm.update",
        "crm.delete",
        "report.view",
        "job.view",
        "member.view",
    },
    "sales_representative": {
        "lead.view",
        "lead.create",
        "opportunity.view",
        "crm.view",
        "crm.create",
        "crm.update",
        "report.view",
        "job.view",
    },
    "marketing_user": {
        "website.view",
        "lead.view",
        "lead.create",
        "business.view",
        "market.view",
        "opportunity.view",
        "marketing.view",
        "marketing.manage",
        "report.view",
        "job.view",
    },
    "viewer": VIEW_PERMISSIONS,
}

ROLE_LABELS = {
    "owner": "Owner",
    "admin": "Admin",
    "manager": "Manager",
    "analyst": "Analyst",
    "sales_manager": "Sales Manager",
    "sales_representative": "Sales Representative",
    "marketing_user": "Marketing User",
    "viewer": "Viewer",
}
