# Generated by Django 5.2.17 on 2026-08-17 12:10

import apps.platform.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAppearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('product_name', models.CharField(default='Seonet', max_length=80)),
                ('legal_name', models.CharField(default='Seonet', max_length=160)),
                ('tagline', models.CharField(default='AI-Powered Business Growth Intelligence', max_length=180)),
                ('description', models.TextField(blank=True, default='AI-powered website intelligence, lead generation, and CRM automation.')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_url', models.URLField(blank=True, default='')),
                ('login_footer', models.CharField(blank=True, default='', max_length=240)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=240)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=16)),
                ('primary_color', models.CharField(default='#0B4F6C', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a 6-digit hex color such as #0B4F6C.')])),
                ('secondary_color', models.CharField(default='#1B9AAA', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a 6-digit hex color such as #0B4F6C.')])),
                ('logo', models.FileField(blank=True, upload_to=apps.platform.models.branding_upload_to)),
                ('logo_dark', models.FileField(blank=True, upload_to=apps.platform.models.branding_upload_to)),
                ('favicon', models.FileField(blank=True, upload_to=apps.platform.models.branding_upload_to)),
                ('app_icon', models.FileField(blank=True, upload_to=apps.platform.models.branding_upload_to)),
            ],
            options={
                'verbose_name': 'Platform appearance',
            },
        ),
    ]
