# Generated by Django 5.2.17 on 2026-08-18 04:28

import apps.platform.landing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_placement_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLanding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('nav', models.JSONField(blank=True, default=apps.platform.landing.default_nav)),
                ('hero_eyebrow', models.CharField(blank=True, default='', max_length=80)),
                ('hero_title', models.CharField(blank=True, default='', max_length=240)),
                ('hero_body', models.TextField(blank=True, default='{description} Crawl, score, discover, and convert inside one tenant — with a control plane for packaging, entitlements, and invoices.')),
                ('hero_primary_cta', models.CharField(blank=True, default='Create workspace', max_length=80)),
                ('hero_secondary_cta', models.CharField(blank=True, default='See the platform', max_length=80)),
                ('hero_secondary_href', models.CharField(blank=True, default='#product', max_length=240)),
                ('stats', models.JSONField(blank=True, default=apps.platform.landing.default_stats)),
                ('pains_eyebrow', models.CharField(blank=True, default='Why teams switch', max_length=80)),
                ('pains_title', models.CharField(blank=True, default='Growth should not start in a spreadsheet.', max_length=240)),
                ('pains_body', models.TextField(blank=True, default='Website quality, account fit, and pipeline belong in one operating system. {product} is built for that workflow — not as a slide deck generator.')),
                ('pains', models.JSONField(blank=True, default=apps.platform.landing.default_pains)),
                ('product_eyebrow', models.CharField(blank=True, default='Product', max_length=80)),
                ('product_title', models.CharField(blank=True, default='Everything {product} ships in one workspace.', max_length=240)),
                ('product_body', models.TextField(blank=True, default='Modules are entitlements, not separate products. Operators assign what a tenant can run. Teams only see what they are licensed to use.')),
                ('steps_eyebrow', models.CharField(blank=True, default='How it works', max_length=80)),
                ('steps_title', models.CharField(blank=True, default='From property to pipeline.', max_length=240)),
                ('steps_body', models.TextField(blank=True, default='The path is explicit: crawl, score, confirm ICP, discover, review, then CRM. Each step is a real job in the workspace.')),
                ('steps', models.JSONField(blank=True, default=apps.platform.landing.default_steps)),
                ('workspace_eyebrow', models.CharField(blank=True, default='Tenant workspace', max_length=80)),
                ('workspace_title', models.CharField(blank=True, default='For the company running growth', max_length=240)),
                ('workspace_body', models.TextField(blank=True, default='Website intelligence, audits, leads, CRM, usage, and billing for your team. Navigation only shows assigned modules.')),
                ('control_plane_eyebrow', models.CharField(blank=True, default='Control plane', max_length=80)),
                ('control_plane_title', models.CharField(blank=True, default='For {owner}', max_length=240)),
                ('control_plane_body', models.TextField(blank=True, default='Tenants, packages, module entitlements, payment gateways, invoicing, and product appearance — one operator console.')),
                ('pricing_eyebrow', models.CharField(blank=True, default='Pricing', max_length=80)),
                ('pricing_title', models.CharField(blank=True, default='Packages that match how the product is actually sold.', max_length=240)),
                ('pricing_body', models.TextField(blank=True, default='These cards come from the live public catalog. Card capture stays off until a gateway is configured. Workspaces can start on invoice.')),
                ('security_eyebrow', models.CharField(blank=True, default='Trust', max_length=80)),
                ('security_title', models.CharField(blank=True, default='Enterprise controls without theatre.', max_length=240)),
                ('security_body', models.TextField(blank=True, default='Claims match the platform: isolation, roles, audit, session cookies, and guarded outbound fetch. No invented certifications.')),
                ('security', models.JSONField(blank=True, default=apps.platform.landing.default_security)),
                ('faq_eyebrow', models.CharField(blank=True, default='FAQ', max_length=80)),
                ('faq_title', models.CharField(blank=True, default='Straight answers.', max_length=240)),
                ('faqs', models.JSONField(blank=True, default=apps.platform.landing.default_faqs)),
                ('cta_title', models.CharField(blank=True, default='Put website intelligence on the same desk as pipeline.', max_length=240)),
                ('cta_body', models.TextField(blank=True, default='Create a workspace, or sign in if {owner} already provisioned your tenant.')),
                ('cta_primary', models.CharField(blank=True, default='Create workspace', max_length=80)),
                ('cta_secondary', models.CharField(blank=True, default='Sign in', max_length=80)),
            ],
            options={
                'verbose_name': 'Platform landing page',
            },
        ),
    ]
