# Generated by Django 5.2.17 on 2026-08-18 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_landing_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('provider', models.CharField(choices=[('google_places', 'Google Places')], max_length=40)),
                ('display_name', models.CharField(max_length=80)),
                ('is_enabled', models.BooleanField(default=False)),
                ('setup_hint', models.TextField(blank=True)),
                ('public_config', models.JSONField(blank=True, default=dict)),
                ('encrypted_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='platformappearance',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2026 SI Global Solutions. All rights reserved.', max_length=240),
        ),
        migrations.AlterField(
            model_name='platformappearance',
            name='description',
            field=models.TextField(blank=True, default='Website intelligence, SEO/AEO/GEO audits, lead discovery, and native CRM in one tenant.'),
        ),
        migrations.AlterField(
            model_name='platformappearance',
            name='login_footer',
            field=models.CharField(blank=True, default='Need a workspace? Ask SI Global Solutions to provision your tenant.', max_length=240),
        ),
        migrations.AlterField(
            model_name='platformappearance',
            name='support_email',
            field=models.EmailField(blank=True, default='hello@siglobalsolutions.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='control_plane_body',
            field=models.TextField(blank=True, default='Tenants, packages, module entitlements, payment gateways, invoicing, landing page, and product appearance — one operator console.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='hero_body',
            field=models.TextField(blank=True, default='{product} crawls your properties, scores SEO, AEO, and GEO, discovers accounts that match your ICP, and converts them in a native CRM. One tenant. One operating system.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='{owner}', max_length=80),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='hero_title',
            field=models.CharField(blank=True, default='Website intelligence that becomes pipeline.', max_length=240),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='pains_body',
            field=models.TextField(blank=True, default='Website quality, account fit, and pipeline belong in one system of record. {product} is built for that workflow — not as a slide deck generator.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='pricing_body',
            field=models.TextField(blank=True, default='Each plan is an entitlement on the tenant: modules, page limits, audit volume, AI credits, and seats. Start on invoice. Card checkout waits until a gateway is enabled.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='pricing_title',
            field=models.CharField(blank=True, default='Packages that match how the product is sold.', max_length=240),
        ),
    ]
