# Generated by Django 5.2.17 on 2026-08-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_lead_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ['sort_order', 'display_name']},
        ),
        migrations.AddField(
            model_name='leadsource',
            name='category',
            field=models.CharField(choices=[('discovery', 'Lead discovery'), ('ai', 'AI models')], db_index=True, default='discovery', max_length=20),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='purpose',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='provider',
            field=models.CharField(choices=[('google_places', 'Google Places'), ('openai', 'OpenAI'), ('anthropic', 'Claude'), ('xai', 'Grok'), ('google_gemini', 'Gemini')], max_length=40),
        ),
    ]
