# Generated by Django 5.2.17 on 2026-08-22 14:49, hand-edited to encrypt existing
# plaintext secrets in place without an unsafe jsonb->text cast on Postgres.

import apps.common.encryption
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    LeadSource = apps.get_model("platform", "LeadSource")
    for source in LeadSource.objects.all():
        source.encrypted_config_v2 = source.encrypted_config or {}
        source.save(update_fields=["encrypted_config_v2"])


def decrypt_back_to_plain(apps, schema_editor):
    LeadSource = apps.get_model("platform", "LeadSource")
    for source in LeadSource.objects.all():
        source.encrypted_config = source.encrypted_config_v2 or {}
        source.save(update_fields=["encrypted_config"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0008_directory_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='encrypted_config_v2',
            field=apps.common.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.RunPython(encrypt_existing_secrets, decrypt_back_to_plain),
        migrations.RemoveField(
            model_name='leadsource',
            name='encrypted_config',
        ),
        migrations.RenameField(
            model_name='leadsource',
            old_name='encrypted_config_v2',
            new_name='encrypted_config',
        ),
    ]
