# Generated by Django 5.2.17 on 2026-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_refresh_landing_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='category',
            field=models.CharField(choices=[('discovery', 'Lead discovery'), ('enrichment', 'Lead enrichment'), ('ai', 'AI models'), ('diagnostics', 'Diagnostics')], db_index=True, default='discovery', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='provider',
            field=models.CharField(choices=[('google_places', 'Google Places'), ('openai', 'OpenAI'), ('anthropic', 'Claude'), ('xai', 'Grok'), ('google_gemini', 'Gemini'), ('google_pagespeed', 'PageSpeed Insights'), ('google_custom_search', 'Google Custom Search'), ('serpapi', 'SerpAPI'), ('yelp', 'Yelp'), ('foursquare', 'Foursquare'), ('geoapify', 'Geoapify'), ('openstreetmap', 'OpenStreetMap'), ('opencorporates', 'OpenCorporates'), ('npi_registry', 'NPI Registry'), ('linkedin_sales_navigator', 'LinkedIn Sales Navigator'), ('yellowpage_pk', 'YellowPage.pk'), ('bbb', 'Better Business Bureau'), ('manta', 'Manta'), ('hunter', 'Hunter'), ('clearbit', 'Clearbit'), ('apollo', 'Apollo'), ('wikidata', 'Wikidata')], max_length=40),
        ),
        migrations.AlterField(
            model_name='platformappearance',
            name='description',
            field=models.TextField(blank=True, default='Website intelligence, licensed keyword ranks, first-party commerce, cited markets, lead discovery, and native CRM in one tenant. Empty stays empty.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='control_plane_body',
            field=models.TextField(blank=True, default='Tenants, packages, module entitlements, licensed search and AI keys, payment gateways, invoicing, landing page, and product appearance — one operator console. Tenants never paste their own Claude key.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='cta_title',
            field=models.CharField(blank=True, default='Put evidence and pipeline on the same desk.', max_length=240),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='hero_body',
            field=models.TextField(blank=True, default='{product} crawls your sites, scores SEO, AEO, and GEO, checks keywords through a licensed first-page sample, and can apply allowlisted fixes. Then it reads your own commerce, cites market signals you ingest, records opportunities, finds matching leads, and converts them in a native CRM. Empty stays empty. No invented #1 ranks or city grades.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='hero_title',
            field=models.CharField(blank=True, default='Website intelligence, honest markets, and pipeline in one workspace.', max_length=240),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='pains_body',
            field=models.TextField(blank=True, default='Website quality, your own commerce, market evidence, and pipeline belong in one system of record. {product} is built for that loop — not as a slide deck or a fake rank report.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='pricing_body',
            field=models.TextField(blank=True, default='Each plan is an entitlement on the tenant: modules, page limits, audit volume, AI credits, and seats. Starter analyzes. Growth adds leads, CRM, and marketing. Scale adds the AI gateway and integrations. Enterprise adds AEO/GEO and commercial terms. Start on invoice. Card checkout waits until a gateway is enabled.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='product_body',
            field=models.TextField(blank=True, default='Modules are entitlements, not separate products. Operators assign what a tenant can run. Teams only see what they are licensed to use. Website intelligence and the growth loop share a login. They do not share scores.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='security_body',
            field=models.TextField(blank=True, default='Claims match the platform: isolation, roles, audit, session cookies, server-side secrets, and guarded outbound fetch. No invented certifications.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='steps_body',
            field=models.TextField(blank=True, default='Each step is a real background job. The UI shows live progress — not a timer. Navigation only lists modules on the package.'),
        ),
        migrations.AlterField(
            model_name='platformlanding',
            name='workspace_body',
            field=models.TextField(blank=True, default='Websites, audits, keyword ranks, allowlisted fixes, business and store sync, markets, opportunities, leads, CRM, marketing, Ask {product}, reports, and billing. Navigation only shows assigned modules.'),
        ),
    ]
