# Generated by Django 5.2.17 on 2026-08-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_alter_leadsource_encrypted_config'),
        ('platform', '0011_alter_leadsource_category_alter_leadsource_provider_and_more'),
    ]

    operations = [
    ]
