# Generated by Django 5.2.17 on 2026-08-27 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0013_alter_platformappearance_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformappearance',
            name='primary_color',
            field=models.CharField(default='#C2410C', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a 6-digit hex color such as #0B4F6C.')]),
        ),
    ]
