# Generated by Django 5.2.17 on 2026-08-21 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=80)),
                ('origin', models.CharField(blank=True, max_length=40)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('why', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='airequest',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='untrusted_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['task', 'created_at'], name='ai_aireques_task_05c79b_idx'),
        ),
        migrations.AddField(
            model_name='askquery',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='askquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='askquery',
            index=models.Index(fields=['tenant', 'created_at'], name='ai_askquery_tenant__3f041d_idx'),
        ),
    ]
