# Generated by Django 5.2.17 on 2026-08-18 04:28

from django.db import migrations, models


def seed_plan_landing_fields(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(code="growth").update(is_featured=True, cta_label="Start Growth")
    Plan.objects.filter(code="starter").update(cta_label="Start trial")
    Plan.objects.filter(code="scale").update(cta_label="Start Scale")
    Plan.objects.filter(code="enterprise").update(is_public=True, cta_label="Talk to sales")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_platform_commerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cta_href',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_plan_landing_fields, migrations.RunPython.noop),
    ]
