# Generated by Django 5.2.17 on 2026-08-22 14:49, hand-edited to encrypt existing
# plaintext secrets in place without an unsafe jsonb->text cast on Postgres.

import apps.common.encryption
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    PaymentGateway = apps.get_model("billing", "PaymentGateway")
    for gateway in PaymentGateway.objects.all():
        gateway.encrypted_config_v2 = gateway.encrypted_config or {}
        gateway.save(update_fields=["encrypted_config_v2"])


def decrypt_back_to_plain(apps, schema_editor):
    PaymentGateway = apps.get_model("billing", "PaymentGateway")
    for gateway in PaymentGateway.objects.all():
        gateway.encrypted_config = gateway.encrypted_config_v2 or {}
        gateway.save(update_fields=["encrypted_config"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='encrypted_config_v2',
            field=apps.common.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.RunPython(encrypt_existing_secrets, decrypt_back_to_plain),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='encrypted_config',
        ),
        migrations.RenameField(
            model_name='paymentgateway',
            old_name='encrypted_config_v2',
            new_name='encrypted_config',
        ),
    ]
