# Generated by Django 5.2.17 on 2026-08-20 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('city', 'City'), ('area', 'Area')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(default='PK', max_length=8)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='markets.geoplace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketFocus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_focuses', to='markets.geoplace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('demand', 'Demand'), ('target_category', 'Target category'), ('purchasing_power', 'Purchasing power'), ('population', 'Population'), ('competition_gap', 'Competition gap'), ('business_density', 'Business density'), ('growth_signals', 'Growth signals'), ('search_interest', 'Search interest')], db_index=True, max_length=40)),
                ('value', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('source_provider', models.CharField(blank=True, max_length=80)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimated', 'Estimated'), ('inferred', 'Inferred'), ('stale', 'Stale')], default='unverified', max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='markets.geoplace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='geoplace',
            index=models.Index(fields=['kind', 'country_code'], name='markets_geo_kind_77d3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='geoplace',
            index=models.Index(fields=['parent', 'kind'], name='markets_geo_parent__b43ee1_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketfocus',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'place'), name='markets_unique_focus'),
        ),
        migrations.AddIndex(
            model_name='marketsignal',
            index=models.Index(fields=['tenant', 'place', 'kind'], name='markets_mar_tenant__c8fc29_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant',), name='markets_one_scoring_profile'),
        ),
    ]
