# Generated by Django 5.2.17 on 2026-08-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'status'], name='jobs_job_tenant__b114ab_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'job_type', 'created_at'], name='jobs_job_tenant__58d3c9_idx'),
        ),
    ]
