DEFAULT_LEAD_SOURCES: list[dict] = [
    {
        "code": "google_places",
        "provider": "google_places",
        "category": "discovery",
        "display_name": "Google Places",
        "purpose": "Find real businesses that match a confirmed ICP and geo market.",
        "is_enabled": False,
        "sort_order": 10,
        "setup_hint": "In Google Cloud Console enable Places API (Text Search), create an API key, and paste it here.",
        "public_config": {
            "env_keys": ["GOOGLE_PLACES_API_KEY", "GOOGLE_MAPS_API_KEY"],
            "homepage_url": "https://developers.google.com/maps/documentation/places/web-service/search-text",
            "requires_key": True,
        },
    },
    {
        "code": "yelp",
        "provider": "yelp",
        "category": "discovery",
        "display_name": "Yelp",
        "purpose": "Business search via the official Yelp Fusion API.",
        "is_enabled": False,
        "sort_order": 11,
        "setup_hint": "Create a Yelp Fusion API key at yelp.com/developers and paste it here. Do not scrape yelp.com.",
        "public_config": {
            "env_keys": ["YELP_API_KEY"],
            "homepage_url": "https://www.yelp.com/",
            "docs_url": "https://docs.developer.yelp.com/docs/fusion-intro",
            "requires_key": True,
        },
    },
    {
        "code": "foursquare",
        "provider": "foursquare",
        "category": "discovery",
        "display_name": "Foursquare",
        "purpose": "Places search via the official Foursquare Places API.",
        "is_enabled": False,
        "sort_order": 12,
        "setup_hint": "Create a Foursquare Places API key and paste it here.",
        "public_config": {
            "env_keys": ["FOURSQUARE_API_KEY"],
            "homepage_url": "https://foursquare.com/",
            "requires_key": True,
        },
    },
    {
        "code": "geoapify",
        "provider": "geoapify",
        "category": "discovery",
        "display_name": "Geoapify",
        "purpose": "Forward geocoding of businesses and amenities via the Geoapify API.",
        "is_enabled": False,
        "sort_order": 13,
        "setup_hint": "Create a Geoapify API key and paste it here.",
        "public_config": {
            "env_keys": ["GEOAPIFY_API_KEY"],
            "homepage_url": "https://www.geoapify.com/",
            "requires_key": True,
        },
    },
    {
        "code": "openstreetmap",
        "provider": "openstreetmap",
        "category": "discovery",
        "display_name": "OpenStreetMap",
        "purpose": "Open Nominatim search for shops, offices, and amenities. No paid key required.",
        "is_enabled": False,
        "sort_order": 14,
        "setup_hint": "Enable this source to use Nominatim. Optional contact email can be stored as the API key for the User-Agent.",
        "public_config": {
            "env_keys": ["NOMINATIM_CONTACT_EMAIL"],
            "homepage_url": "https://www.openstreetmap.org/",
            "search_url": "https://nominatim.openstreetmap.org/search",
            "requires_key": False,
        },
    },
    {
        "code": "opencorporates",
        "provider": "opencorporates",
        "category": "discovery",
        "display_name": "OpenCorporates",
        "purpose": "Legal company records via the OpenCorporates search API.",
        "is_enabled": False,
        "sort_order": 15,
        "setup_hint": "Create an OpenCorporates API token and paste it here. Anonymous access is heavily rate-limited.",
        "public_config": {
            "env_keys": ["OPENCORPORATES_API_TOKEN"],
            "homepage_url": "https://opencorporates.com/",
            "requires_key": True,
        },
    },
    {
        "code": "npi_registry",
        "provider": "npi_registry",
        "category": "discovery",
        "display_name": "NPI Registry",
        "purpose": "US healthcare organizations from the official CMS NPI Registry. No key required.",
        "is_enabled": False,
        "sort_order": 16,
        "setup_hint": "Enable this source for US healthcare ICPs. The CMS NPI Registry is a public government API.",
        "public_config": {
            "homepage_url": "https://npiregistry.cms.hhs.gov/",
            "requires_key": False,
        },
    },
    {
        "code": "linkedin_sales_navigator",
        "provider": "linkedin_sales_navigator",
        "category": "discovery",
        "display_name": "LinkedIn Sales Navigator",
        "purpose": "Paid SNAP / Sales Navigator company search using your LinkedIn partner token.",
        "is_enabled": False,
        "sort_order": 17,
        "setup_hint": "LinkedIn requires approved Sales Navigator API (SNAP) access. Paste the OAuth access token. You can update Search URL if LinkedIn issues a newer endpoint.",
        "public_config": {
            "env_keys": ["LINKEDIN_ACCESS_TOKEN", "LINKEDIN_SALES_NAV_TOKEN"],
            "homepage_url": "https://www.linkedin.com/sales/",
            "docs_url": "https://learn.microsoft.com/en-us/linkedin/sales/",
            "search_url": "https://api.linkedin.com/rest/salesApiSearch",
            "requires_key": True,
        },
    },
    {
        "code": "yellowpage_pk",
        "provider": "yellowpage_pk",
        "category": "discovery",
        "display_name": "YellowPage.pk",
        "purpose": "Pakistan B2B directory. Wired only through a licensed search API you configure.",
        "is_enabled": False,
        "sort_order": 18,
        "setup_hint": "YellowPage.pk does not publish a public search API. After you have licensed access, paste the search endpoint and API key here. Seonet will not scrape yellowpage.pk.",
        "public_config": {
            "env_keys": ["YELLOWPAGE_PK_API_KEY"],
            "homepage_url": "https://yellowpage.pk/",
            "search_url": "",
            "auth_style": "bearer",
            "results_path": "results",
            "name_field": "name",
            "id_field": "id",
            "address_field": "address",
            "website_field": "website",
            "industry_field": "category",
            "requires_key": True,
        },
    },
    {
        "code": "bbb",
        "provider": "bbb",
        "category": "discovery",
        "display_name": "Better Business Bureau",
        "purpose": "Accredited US/Canada businesses via a licensed BBB API endpoint you configure.",
        "is_enabled": False,
        "sort_order": 19,
        "setup_hint": "BBB business search is partner-licensed. Paste the official API base search URL and key. Seonet will not scrape bbb.org.",
        "public_config": {
            "env_keys": ["BBB_API_KEY"],
            "homepage_url": "https://www.bbb.org/",
            "search_url": "",
            "auth_style": "header",
            "results_path": "results",
            "name_field": "name",
            "id_field": "id",
            "address_field": "address",
            "website_field": "website",
            "industry_field": "category",
            "requires_key": True,
        },
    },
    {
        "code": "manta",
        "provider": "manta",
        "category": "discovery",
        "display_name": "Manta",
        "purpose": "US small-business directory via a licensed search API you configure.",
        "is_enabled": False,
        "sort_order": 21,
        "setup_hint": "Manta does not publish a public search API. Paste a licensed search endpoint and key. Seonet will not scrape manta.com.",
        "public_config": {
            "env_keys": ["MANTA_API_KEY"],
            "homepage_url": "https://www.manta.com/",
            "search_url": "",
            "auth_style": "bearer",
            "results_path": "results",
            "name_field": "name",
            "id_field": "id",
            "address_field": "address",
            "website_field": "website",
            "industry_field": "industry",
            "requires_key": True,
        },
    },
    {
        "code": "hunter",
        "provider": "hunter",
        "category": "enrichment",
        "display_name": "Hunter",
        "purpose": "Find published work emails for a company domain via the Hunter Domain Search API.",
        "is_enabled": False,
        "sort_order": 30,
        "setup_hint": "Create a Hunter API key at hunter.io and paste it here. Seonet stores only emails Hunter returns.",
        "public_config": {
            "env_keys": ["HUNTER_API_KEY"],
            "homepage_url": "https://hunter.io/",
            "docs_url": "https://hunter.io/api-documentation/v2",
            "requires_key": True,
        },
    },
    {
        "code": "clearbit",
        "provider": "clearbit",
        "category": "enrichment",
        "display_name": "Clearbit",
        "purpose": "Firmographic enrichment (website, industry, employees, LinkedIn) from a domain via Clearbit.",
        "is_enabled": False,
        "sort_order": 31,
        "setup_hint": "Paste a Clearbit Enrichment API key. Empty Clearbit fields stay empty.",
        "public_config": {
            "env_keys": ["CLEARBIT_API_KEY"],
            "homepage_url": "https://clearbit.com/",
            "requires_key": True,
        },
    },
    {
        "code": "apollo",
        "provider": "apollo",
        "category": "enrichment",
        "display_name": "Apollo",
        "purpose": "Organization enrichment from a domain via the Apollo API.",
        "is_enabled": False,
        "sort_order": 32,
        "setup_hint": "Paste an Apollo API key. Seonet does not invent contacts Apollo does not return.",
        "public_config": {
            "env_keys": ["APOLLO_API_KEY"],
            "homepage_url": "https://www.apollo.io/",
            "requires_key": True,
        },
    },
    {
        "code": "wikidata",
        "provider": "wikidata",
        "category": "enrichment",
        "display_name": "Wikidata",
        "purpose": "Open firmographics (website, industry, country, employees) from Wikidata SPARQL. No key required.",
        "is_enabled": True,
        "sort_order": 33,
        "setup_hint": "Enabled by default. Uses the public Wikidata query service. No paid key.",
        "public_config": {
            "homepage_url": "https://www.wikidata.org/",
            "requires_key": False,
        },
    },
    {
        "code": "openai",
        "provider": "openai",
        "category": "ai",
        "display_name": "OpenAI",
        "purpose": "ICP extraction, audit summaries, recommendations, and lead scoring.",
        "is_enabled": False,
        "sort_order": 40,
        "setup_hint": "Create a secret key in the OpenAI platform and paste it here. Used first when several AI sources are enabled.",
        "public_config": {"model": "gpt-4o-mini", "env_keys": ["OPENAI_API_KEY"]},
    },
    {
        "code": "anthropic",
        "provider": "anthropic",
        "category": "ai",
        "display_name": "Claude",
        "purpose": "Long-context analysis for audits, recommendations, and ICP parsing.",
        "is_enabled": False,
        "sort_order": 41,
        "setup_hint": "Create an API key in the Anthropic console and paste it here.",
        "public_config": {"model": "claude-sonnet-4-5", "env_keys": ["ANTHROPIC_API_KEY"]},
    },
    {
        "code": "xai",
        "provider": "xai",
        "category": "ai",
        "display_name": "Grok",
        "purpose": "Fallback completions for ICP, summaries, and scoring.",
        "is_enabled": False,
        "sort_order": 42,
        "setup_hint": "Create an API key in the xAI console and paste it here.",
        "public_config": {"model": "grok-3-mini", "env_keys": ["XAI_API_KEY"]},
    },
    {
        "code": "google_gemini",
        "provider": "google_gemini",
        "category": "ai",
        "display_name": "Gemini",
        "purpose": "Fallback completions and structured extraction.",
        "is_enabled": False,
        "sort_order": 43,
        "setup_hint": "In Google AI Studio or Cloud, enable Gemini and paste an API key here. This is separate from the Places key.",
        "public_config": {"model": "gemini-2.0-flash", "env_keys": ["GEMINI_API_KEY", "GOOGLE_AI_API_KEY"]},
    },
    {
        "code": "google_pagespeed",
        "provider": "google_pagespeed",
        "category": "diagnostics",
        "display_name": "PageSpeed Insights",
        "purpose": "Optional lab/field overlay for LCP, INP, and CLS. Never replaces Seonet crawl TTFB or the technical score.",
        "is_enabled": False,
        "sort_order": 90,
        "setup_hint": "In Google Cloud Console enable PageSpeed Insights API, create an API key, and paste it here. Env fallback: PAGESPEED_API_KEY or GOOGLE_PAGESPEED_API_KEY.",
        "public_config": {"env_keys": ["PAGESPEED_API_KEY", "GOOGLE_PAGESPEED_API_KEY"]},
    },
    {
        "code": "google_custom_search",
        "provider": "google_custom_search",
        "category": "diagnostics",
        "display_name": "Google Custom Search",
        "purpose": "Official Google JSON API to see whether this website’s stored keywords appear on the first page of a configured search engine. Not a scrape of google.com, and not a promised #1 rank.",
        "is_enabled": False,
        "sort_order": 91,
        "setup_hint": "In Google Cloud enable Custom Search API, create an API key, and create a Programmable Search Engine. Paste the API key here and the engine ID (cx) in Licensed search URL. Env: GOOGLE_CUSTOM_SEARCH_API_KEY and GOOGLE_CSE_ID.",
        "public_config": {"env_keys": ["GOOGLE_CUSTOM_SEARCH_API_KEY", "GOOGLE_CSE_CX"], "docs_url": "https://developers.google.com/custom-search/v1/overview"},
    },
    {
        "code": "serpapi",
        "provider": "serpapi",
        "category": "diagnostics",
        "display_name": "SerpAPI",
        "purpose": "Licensed Google SERP lookup for stored website keywords. Positions are from the provider sample, not invented ranks.",
        "is_enabled": False,
        "sort_order": 92,
        "setup_hint": "Create a SerpAPI key and paste it here. Env fallback: SERPAPI_API_KEY.",
        "public_config": {"env_keys": ["SERPAPI_API_KEY"], "docs_url": "https://serpapi.com"},
    },
]
