from django.urls import path

from apps.platform.telemetry import (
    PlatformAskListView,
    PlatformPageViewListView,
    PlatformPromptListView,
    PlatformWorkspaceActivityView,
)
from apps.platform.views import (
    PlatformAdminDetailView,
    PlatformAdminListView,
    PlatformAdminResetPasswordView,
    PlatformFeatureDetailView,
    PlatformGatewayDetailView,
    PlatformGatewayListView,
    PlatformInvoiceDetailView,
    PlatformInvoiceIssueView,
    PlatformInvoiceListView,
    PlatformInvoicePayView,
    PlatformInvoiceVoidView,
    PlatformModuleDetailView,
    PlatformModuleFeatureListView,
    PlatformModuleListView,
    PlatformOverviewView,
    PlatformPackageDetailView,
    PlatformPackageListView,
    PlatformSubscriptionDetailView,
    PlatformSubscriptionListView,
    PlatformTenantDetailView,
    PlatformTenantListView,
    PlatformTenantModuleView,
    PlatformTenantPlanView,
    PlatformAppearanceView,
    PlatformAppearanceAssetView,
    PlatformLandingView,
    PlatformLeadSourceDetailView,
    PlatformLeadSourceListView,
    PlatformLeadSourceTestView,
)

urlpatterns = [
    path("admins/", PlatformAdminListView.as_view(), name="platform-admins"),
    path("admins/<uuid:id>/", PlatformAdminDetailView.as_view(), name="platform-admin-detail"),
    path("admins/<uuid:id>/reset-password/", PlatformAdminResetPasswordView.as_view(), name="platform-admin-reset-password"),
    path("overview/", PlatformOverviewView.as_view(), name="platform-overview"),
    path("tenants/", PlatformTenantListView.as_view(), name="platform-tenants"),
    path("tenants/<uuid:id>/", PlatformTenantDetailView.as_view(), name="platform-tenant-detail"),
    path("tenants/<uuid:id>/modules/", PlatformTenantModuleView.as_view(), name="platform-tenant-modules"),
    path("tenants/<uuid:id>/plan/", PlatformTenantPlanView.as_view(), name="platform-tenant-plan"),
    path("modules/", PlatformModuleListView.as_view(), name="platform-modules"),
    path("modules/<uuid:id>/", PlatformModuleDetailView.as_view(), name="platform-module-detail"),
    path("modules/<uuid:id>/features/", PlatformModuleFeatureListView.as_view(), name="platform-module-features"),
    path("features/<uuid:id>/", PlatformFeatureDetailView.as_view(), name="platform-feature-detail"),
    path("packages/", PlatformPackageListView.as_view(), name="platform-packages"),
    path("packages/<uuid:id>/", PlatformPackageDetailView.as_view(), name="platform-package-detail"),
    path("gateways/", PlatformGatewayListView.as_view(), name="platform-gateways"),
    path("gateways/<uuid:id>/", PlatformGatewayDetailView.as_view(), name="platform-gateway-detail"),
    path("invoices/", PlatformInvoiceListView.as_view(), name="platform-invoices"),
    path("invoices/<uuid:id>/", PlatformInvoiceDetailView.as_view(), name="platform-invoice-detail"),
    path("invoices/<uuid:id>/issue/", PlatformInvoiceIssueView.as_view(), name="platform-invoice-issue"),
    path("invoices/<uuid:id>/mark-paid/", PlatformInvoicePayView.as_view(), name="platform-invoice-pay"),
    path("invoices/<uuid:id>/void/", PlatformInvoiceVoidView.as_view(), name="platform-invoice-void"),
    path("subscriptions/", PlatformSubscriptionListView.as_view(), name="platform-subscriptions"),
    path("subscriptions/<uuid:id>/", PlatformSubscriptionDetailView.as_view(), name="platform-subscription-detail"),
    path("lead-sources/", PlatformLeadSourceListView.as_view(), name="platform-lead-sources"),
    path("lead-sources/<uuid:id>/", PlatformLeadSourceDetailView.as_view(), name="platform-lead-source-detail"),
    path("lead-sources/<uuid:id>/test/", PlatformLeadSourceTestView.as_view(), name="platform-lead-source-test"),
    path("appearance/", PlatformAppearanceView.as_view(), name="platform-appearance"),
    path("appearance/assets/<str:slot>/", PlatformAppearanceAssetView.as_view(), name="platform-appearance-asset"),
    path("landing/", PlatformLandingView.as_view(), name="platform-landing"),
    path("telemetry/prompts/", PlatformPromptListView.as_view(), name="platform-telemetry-prompts"),
    path("telemetry/asks/", PlatformAskListView.as_view(), name="platform-telemetry-asks"),
    path("telemetry/pages/", PlatformPageViewListView.as_view(), name="platform-telemetry-pages"),
    path("telemetry/activity/", PlatformWorkspaceActivityView.as_view(), name="platform-telemetry-activity"),
]
