# Generated by Django 5.2.17 on 2026-08-17 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('raw_input', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('employee_count', models.CharField(blank=True, max_length=40)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('origin', models.CharField(default='heuristic', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], db_index=True, default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('zones', models.PositiveIntegerField(default=0)),
                ('queries', models.PositiveIntegerField(default=0)),
                ('discovered', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('unique_count', models.PositiveIntegerField(default=0)),
                ('qualified', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='leads.icp')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_searches', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('source_record_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('unqualified', 'Unqualified')], db_index=True, default='new', max_length=20)),
                ('lead_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('opportunity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icp_fit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location_fit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('industry_fit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crm_synced', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('origin', models.CharField(default='fact', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('lists', models.ManyToManyField(blank=True, related_name='leads', to='leads.leadlist')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsearch')),
            ],
        ),
        migrations.AddIndex(
            model_name='icp',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_icp_tenant__7d9d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadlist',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_leadl_tenant__684ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsearch',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_leads_tenant__d78b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status', 'lead_score'], name='leads_lead_tenant__efb52d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'company_name'], name='leads_lead_tenant__bb7465_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('tenant', 'source', 'source_record_id')},
        ),
    ]
