# Generated by Django 5.2.17 on 2026-08-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='employee_count',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
