# Generated by Django 5.2.17 on 2026-08-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_tenant_integrations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crmconnection',
            new_name='integration_tenant__d3e474_idx',
            old_name='integration_tenant__prov_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantapitoken',
            new_name='integration_tenant__23fbe9_idx',
            old_name='integration_tenant__tok_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantapitoken',
            new_name='integration_prefix_a85563_idx',
            old_name='integration_prefix_idx',
        ),
    ]
