# Generated by Django 5.2.17 on 2026-08-22 14:49, hand-edited to encrypt existing
# plaintext secrets in place without an unsafe jsonb->text cast on Postgres.

import apps.common.encryption
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    CRMConnection = apps.get_model("integrations", "CRMConnection")
    for connection in CRMConnection.objects.all():
        connection.encrypted_config_v2 = connection.encrypted_config or {}
        connection.save(update_fields=["encrypted_config_v2"])


def decrypt_back_to_plain(apps, schema_editor):
    CRMConnection = apps.get_model("integrations", "CRMConnection")
    for connection in CRMConnection.objects.all():
        connection.encrypted_config = connection.encrypted_config_v2 or {}
        connection.save(update_fields=["encrypted_config"])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_rename_integration_tenant__prov_idx_integration_tenant__d3e474_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconnection',
            name='encrypted_config_v2',
            field=apps.common.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.RunPython(encrypt_existing_secrets, decrypt_back_to_plain),
        migrations.RemoveField(
            model_name='crmconnection',
            name='encrypted_config',
        ),
        migrations.RenameField(
            model_name='crmconnection',
            old_name='encrypted_config_v2',
            new_name='encrypted_config',
        ),
    ]
