# Generated by Django 5.2.17 on 2026-08-17 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('why_it_matters', models.TextField()),
                ('affected_urls', models.JSONField(blank=True, default=list)),
                ('evidence', models.TextField()),
                ('recommendation', models.TextField()),
                ('estimated_effort', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=20)),
                ('origin', models.CharField(default='fact', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('verified_finding', models.TextField()),
                ('ai_interpretation', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('origin', models.CharField(default='recommendation', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('pages_discovered', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=800)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(default='fact', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
