# Generated by Django 5.2.17 on 2026-08-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('jobs', '0003_initial'),
        ('tenants', '0002_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='websites.website'),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='audits.audit'),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditrecommendation',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.audit'),
        ),
        migrations.AddField(
            model_name='auditrecommendation',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_rows', to='audits.auditissue'),
        ),
        migrations.AddField(
            model_name='auditrecommendation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='crawl',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawls', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='crawl',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='crawl',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='websites.website'),
        ),
        migrations.AddField(
            model_name='audit',
            name='crawl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='audits.crawl'),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='crawl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='audits.crawl'),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['tenant', 'audit', 'severity'], name='audits_audi_tenant__41fda6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrecommendation',
            index=models.Index(fields=['tenant', 'created_at'], name='audits_audi_tenant__acf853_idx'),
        ),
        migrations.AddIndex(
            model_name='crawl',
            index=models.Index(fields=['tenant', 'created_at'], name='audits_craw_tenant__1eba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['tenant', 'website', 'created_at'], name='audits_audi_tenant__dfdd15_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['tenant', 'status'], name='audits_audi_tenant__b5e87a_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlpage',
            index=models.Index(fields=['tenant', 'created_at'], name='audits_craw_tenant__d22fc3_idx'),
        ),
    ]
