# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="signals",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="audit",
            name="summary",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
