# Generated by Django 5.2.17 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_crawl_signals_audit_summary'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crawlpage',
            name='audits_craw_tenant__d22fc3_idx',
        ),
        migrations.AddField(
            model_name='auditissue',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='compression',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='html_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='http_protocol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='page_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='transfer_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlpage',
            name='ttfb_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['tenant', 'audit', 'code'], name='audits_audi_tenant__a0e632_idx'),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['tenant', 'audit', 'category'], name='audits_audi_tenant__ad79f4_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlpage',
            index=models.Index(fields=['tenant', 'crawl', 'ttfb_ms'], name='audits_craw_tenant__79e936_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlpage',
            index=models.Index(fields=['tenant', 'crawl', 'page_score'], name='audits_craw_tenant__3ede2c_idx'),
        ),
    ]
