# Generated by Django 5.2.17 on 2026-08-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_restore_tenant_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditissue',
            new_name='audits_audi_tenant__02b058_idx',
            old_name='audits_issue_tenant_created',
        ),
    ]
