# Generated by Django 5.2.17 on 2026-08-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'created_at'], name='tenants_ten_status_3cf878_idx'),
        ),
        migrations.AddField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='tenants_mem_user_id_b78f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'status'], name='tenants_mem_tenant__3b8b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('tenant', 'user')},
        ),
    ]
