# Generated by Django 5.2.17 on 2026-08-20 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('offer', 'Offer'), ('content', 'Content')], default='offer', max_length=20)),
                ('audience_type', models.CharField(choices=[('lead_list', 'Lead list'), ('commerce_city', 'Imported customers in a city'), ('opportunity', 'Opportunity-linked leads')], default='lead_list', max_length=32)),
                ('city', models.CharField(blank=True, max_length=160)),
                ('offer_title', models.CharField(blank=True, max_length=255)),
                ('offer_body', models.TextField(blank=True)),
                ('audience_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_note', models.TextField(blank=True)),
                ('lead_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='leads.leadlist')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='opportunities.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='marketing_c_tenant__e998ae_idx')],
            },
        ),
    ]
