# Generated by Django 5.2.17 on 2026-08-20 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(default='csv', max_length=80)),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(default='csv', max_length=80)),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommerceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=160)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], db_index=True, default='placed', max_length=20)),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('source', models.CharField(default='csv', max_length=80)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business.commercecustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.commerceorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='business.catalogproduct')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('retail', 'Retail'), ('services', 'Services'), ('b2b', 'B2B'), ('manufacturing', 'Manufacturing')], default='ecommerce', max_length=32)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('current_market', models.CharField(blank=True, max_length=160)),
                ('goal', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant',), name='business_one_profile_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['tenant', 'sku'], name='business_ca_tenant__454629_idx'),
        ),
        migrations.AddIndex(
            model_name='commercecustomer',
            index=models.Index(fields=['tenant', 'created_at'], name='business_co_tenant__e6b7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceorder',
            index=models.Index(fields=['tenant', 'ordered_at'], name='business_co_tenant__362b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceorderitem',
            index=models.Index(fields=['tenant', 'created_at'], name='business_co_tenant__fb846e_idx'),
        ),
    ]
