# Generated by Django 5.2.17 on 2026-08-21 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('reviewer', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(max_length=80)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=16)),
                ('origin', models.CharField(default='fact', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='commercecustomer',
            name='external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['tenant', 'source', 'external_id'], name='business_ca_tenant__503e80_idx'),
        ),
        migrations.AddField(
            model_name='commercereview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='business.catalogproduct'),
        ),
        migrations.AddField(
            model_name='commercereview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='commercereview',
            index=models.Index(fields=['tenant', 'source', 'created_at'], name='business_co_tenant__242a32_idx'),
        ),
    ]
