# Generated by Django 5.2.17 on 2026-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_store_sync_and_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='last_expert',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
