# Generated by Django 5.2.17 on 2026-08-26 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_last_expert'),
        ('jobs', '0003_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('orders', 'Orders'), ('products', 'Products')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='commerceorder',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business.importbatch'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['tenant', 'kind', 'created_at'], name='business_im_tenant__c6b014_idx'),
        ),
    ]
