# Generated by Django 5.2.17 on 2026-08-20 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('markets', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('business', 'Business'), ('market', 'Market'), ('product', 'Product'), ('geographic', 'Geographic'), ('customer', 'Customer'), ('cross_sell', 'Cross-sell'), ('upsell', 'Upsell')], db_index=True, max_length=32)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evidence', models.TextField()),
                ('recommended_action', models.TextField()),
                ('potential_impact', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origin', models.CharField(default='user', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('geo_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='markets.geoplace')),
                ('related_leads', models.ManyToManyField(blank=True, related_name='growth_opportunities', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'type'], name='opportuniti_tenant__3346f7_idx')],
            },
        ),
    ]
