PRODUCT_MODULES: list[dict[str, object]] = [
    {
        "code": "websites",
        "name": "Website Intelligence",
        "description": "Connect properties, crawl pages, check keyword ranks in the background, and keep website health as a first-class workspace object.",
        "category": "intelligence",
        "sort_order": 10,
    },
    {
        "code": "audits",
        "name": "Audits & Scoring",
        "description": "Deterministic SEO, AEO, GEO, and opportunity scores, plus allowlisted on-page fixes. Not a black-box grade or a Google rank.",
        "category": "intelligence",
        "sort_order": 20,
    },
    {
        "code": "aeo",
        "name": "AEO / GEO",
        "description": "Answer-engine and generative-engine readiness so you are visible beyond classic ten-blue-links SEO.",
        "category": "intelligence",
        "sort_order": 25,
    },
    {
        "code": "business",
        "name": "Business Analysis",
        "description": "Understand the tenant’s own business from imported products, customers, and orders. KPIs are hidden until those rows exist.",
        "category": "growth",
        "sort_order": 26,
    },
    {
        "code": "markets",
        "name": "Market Intelligence",
        "description": "Cited market briefs over your commerce and ingested signals. Scores stay empty until this workspace has sources — no invented city grades.",
        "category": "growth",
        "sort_order": 27,
    },
    {
        "code": "opportunities",
        "name": "Opportunities",
        "description": "Actionable growth opportunities connecting business analysis and market intelligence. Separate from native CRM deals.",
        "category": "growth",
        "sort_order": 28,
    },
    {
        "code": "leads",
        "name": "Lead Intelligence",
        "description": "ICP, geo markets, discovery, enrichment, and scoring with a human review step before CRM.",
        "category": "growth",
        "sort_order": 30,
    },
    {
        "code": "marketing",
        "name": "Marketing",
        "description": "Campaigns built from existing lead lists or imported customer cities. Audience size is a count, not an invented open rate.",
        "category": "growth",
        "sort_order": 35,
    },
    {
        "code": "crm",
        "name": "Native CRM",
        "description": "Companies, contacts, pipelines, deals, and activities in the same tenant as the intelligence that found them.",
        "category": "growth",
        "sort_order": 40,
    },
    {
        "code": "ai",
        "name": "AI Gateway",
        "description": "Claude, OpenAI, Grok, or Gemini with package credits. Keyword suggestions, advisors, and expert language are tagged inference — never stored as fact.",
        "category": "intelligence",
        "sort_order": 50,
    },
    {
        "code": "integrations",
        "name": "Integrations",
        "description": "Connect HubSpot, Odoo, and other systems when you are ready — without giving up the native workflow.",
        "category": "operations",
        "sort_order": 60,
    },
    {
        "code": "reports",
        "name": "Reports & Usage",
        "description": "Exportable intelligence summaries plus metered credits, seats, and invoices on the assigned package.",
        "category": "operations",
        "sort_order": 70,
    },
]

MODULE_FEATURES: list[tuple[str, str, str, str]] = [
    ("websites", "website.create", "Add and manage websites", "Create properties and keep crawl configuration on the tenant."),
    ("audits", "audit.run", "Run website audits", "Queue deterministic SEO, AEO, GEO, and opportunity scoring jobs."),
    ("audits", "audit.recommendations", "Audit recommendations", "Turn scored issues into assignable next actions."),
    ("aeo", "aeo.analysis", "AEO and GEO analysis", "Measure answer-engine and generative-engine readiness."),
    ("business", "business.profile", "Business profile and commerce", "Store the workspace business profile, import CSV, or sync Shopify, WooCommerce, Etsy, and eBay."),
    ("markets", "market.score", "Market scoring", "Configure weights and ingest market signals. No invented city scores."),
    ("opportunities", "opportunity.track", "Growth opportunities", "Record explainable opportunities with evidence and recommended action."),
    ("marketing", "marketing.campaigns", "Campaigns", "Plan offers against existing lead lists or imported customers. Sending records a count; it does not dispatch email."),
    ("leads", "lead.discover", "Lead discovery", "Find accounts that match a confirmed ICP and geo market."),
    ("leads", "lead.enrich", "Lead enrichment", "Fill missing website, email, phone, location, and industry from the company site, Wikidata, enabled discovery APIs, and licensed Hunter, Clearbit, Apollo, or search keys. Empty stays empty."),
    ("crm", "crm.pipeline", "Pipeline and deal management", "Move qualified companies into deals, activities, and reporting."),
    ("reports", "report.export", "Report exports", "Export intelligence summaries for the workspace."),
    ("integrations", "integration.connect", "Connect third-party CRMs", "Optional HubSpot and Odoo connections without replacing native CRM."),
    ("ai", "ai.insights", "AI-assisted insights", "Provider-backed assistance with usage logging. Output is not stored as fact."),
]

DEFAULT_PACKAGES: list[dict[str, object]] = [
    {
        "code": "starter",
        "name": "Starter",
        "description": "Website intelligence and audits for a focused growth team.",
        "price_amount": "49.00",
        "interval": "month",
        "trial_days": 14,
        "max_pages": 25,
        "max_audits_per_month": 20,
        "ai_credits": 1000,
        "max_users": 5,
        "modules": ["websites", "audits", "business", "markets", "opportunities"],
        "cta_label": "Start trial",
        "sort_order": 10,
    },
    {
        "code": "growth",
        "name": "Growth",
        "description": "Turn audits into pipeline with lead intelligence and native CRM.",
        "price_amount": "149.00",
        "interval": "month",
        "trial_days": 14,
        "max_pages": 100,
        "max_audits_per_month": 80,
        "ai_credits": 8000,
        "max_users": 20,
        "modules": ["websites", "audits", "business", "markets", "opportunities", "leads", "crm", "reports", "marketing"],
        "is_featured": True,
        "cta_label": "Start Growth",
        "sort_order": 20,
    },
    {
        "code": "scale",
        "name": "Scale",
        "description": "Full commercial suite including AI gateway and integrations.",
        "price_amount": "399.00",
        "interval": "month",
        "trial_days": 7,
        "max_pages": 500,
        "max_audits_per_month": 400,
        "ai_credits": 40000,
        "max_users": 100,
        "modules": ["websites", "audits", "business", "markets", "opportunities", "leads", "crm", "reports", "marketing", "integrations", "ai"],
        "cta_label": "Start Scale",
        "sort_order": 30,
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "description": "All modules including AEO/GEO, custom entitlements, and commercial terms.",
        "price_amount": "0.00",
        "interval": "month",
        "trial_days": 0,
        "max_pages": 5000,
        "max_audits_per_month": 5000,
        "ai_credits": 250000,
        "max_users": 1000,
        "modules": ["websites", "audits", "business", "markets", "opportunities", "leads", "crm", "reports", "marketing", "integrations", "ai", "aeo"],
        "is_public": True,
        "cta_label": "Talk to sales",
        "sort_order": 40,
    },
]

DEFAULT_GATEWAYS: list[dict[str, object]] = [
    {
        "code": "manual",
        "provider": "manual",
        "display_name": "Manual / bank transfer",
        "is_enabled": True,
        "is_default": True,
        "test_mode": False,
        "public_config": {
            "instructions": "Pay issued invoices by bank transfer. Workspace access resumes after SI Global confirms the payment in the control plane."
        },
    },
    {
        "code": "stripe",
        "provider": "stripe",
        "display_name": "Stripe",
        "is_enabled": False,
        "is_default": False,
        "test_mode": True,
        "public_config": {},
    },
    {
        "code": "paypal",
        "provider": "paypal",
        "display_name": "PayPal",
        "is_enabled": False,
        "is_default": False,
        "test_mode": True,
        "public_config": {},
    },
]
